import {env} from 'cloudflare:workers';
import {getWorkspaceUser} from '@/app/workspace-auth';
import {limited,resolveOwner,response} from '@/lib/production-api';
import {readEvidence} from '@/lib/hours-api';
import {logError} from '@/lib/log';

const MAX_PHOTO_BYTES=5_000_000,MAX_PHOTOS=300,MAX_ACCOUNT_BYTES=500_000_000;
const uuid=(value:string|null)=>!!value&&/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
async function ownerPrefix(email:string){const bytes=new TextEncoder().encode(email.trim().toLowerCase()),hash=await crypto.subtle.digest('SHA-256',bytes);return 'technical-sheets/'+[...new Uint8Array(hash)].map(n=>n.toString(16).padStart(2,'0')).join('')+'/';}
const validImage=(type:string,bytes:Uint8Array)=>type==='image/png'?[137,80,78,71,13,10,26,10].every((n,i)=>bytes[i]===n):type==='image/jpeg'&&bytes[0]===255&&bytes[1]===216&&bytes[2]===255;
function uploadAllowed(req:Request){const origin=req.headers.get('origin');return req.headers.get('x-prumo-request')==='1'&&req.headers.get('sec-fetch-site')!=='cross-site'&&(!origin||origin===new URL(req.url).origin)}

export async function GET(req:Request){try{const user=await getWorkspaceUser('sheets:read'),id=new URL(req.url).searchParams.get('sheet');if(!user)return response({error:'Acesso não autorizado.'},401);if(!env.DB||!env.BUCKET||!uuid(id))return response({error:'Foto não encontrada.'},404);const owner=await resolveOwner(env.DB,user);if(await limited(env.DB,owner))return response({error:'Muitas solicitações. Aguarde um minuto.'},429);const sheet=await env.DB.prepare('SELECT id FROM technical_sheets WHERE id=? AND owner=?').bind(id,owner).first();if(!sheet)return response({error:'Foto não encontrada.'},404);const object=await env.BUCKET.get((await ownerPrefix(owner))+id);if(!object)return response({error:'Foto não encontrada.'},404);return new Response(object.body,{headers:{'Content-Type':object.httpMetadata?.contentType||'image/jpeg','Content-Disposition':'inline; filename="foto"','Cache-Control':'private, max-age=300','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'; sandbox",'Referrer-Policy':'no-referrer'}})}catch(err){logError('technical-photo','read_error',err);return response({error:'Não foi possível abrir a foto.',code:'db_error'},503)}}

export async function POST(req:Request){try{const user=await getWorkspaceUser('sheets:write'),id=new URL(req.url).searchParams.get('sheet');if(!user)return response({error:'Acesso não autorizado.'},401);if(!env.DB||!env.BUCKET)return response({error:'Armazenamento indisponível.'},503);if(!uuid(id)||!uploadAllowed(req))return response({error:'Solicitação não permitida.'},403);const owner=await resolveOwner(env.DB,user);if(await limited(env.DB,owner))return response({error:'Muitas solicitações. Aguarde um minuto.'},429);const sheet=await env.DB.prepare('SELECT id FROM technical_sheets WHERE id=? AND owner=? AND archived=0').bind(id,owner).first();if(!sheet)return response({error:'Salve uma ficha ativa antes de adicionar a foto.'},404);const type=(req.headers.get('content-type')||'').split(';')[0].trim().toLowerCase();if(!['image/jpeg','image/png'].includes(type))return response({error:'Use uma imagem JPG ou PNG.'},400);let bytes:Uint8Array;try{bytes=await readEvidence(req,MAX_PHOTO_BYTES)}catch{return response({error:'A foto deve ter até 5 MB.',code:'too_large'},413)}if(!validImage(type,bytes))return response({error:'O conteúdo do arquivo não corresponde a uma imagem JPG ou PNG válida.',code:'invalid'},400);const prefix=await ownerPrefix(owner),objects=await env.BUCKET.list({prefix,limit:MAX_PHOTOS+1}),current=objects.objects.reduce((sum,item)=>sum+(item.size??0),0),existing=await env.BUCKET.head(prefix+id);if(!existing&&objects.objects.length>=MAX_PHOTOS||current-(existing?.size??0)+bytes.length>MAX_ACCOUNT_BYTES)return response({error:'Limite de fotos da conta atingido.',code:'quota'},413);await env.BUCKET.put(prefix+id,bytes,{httpMetadata:{contentType:type}});return response({ok:true,version:new Date().toISOString()})}catch(err){logError('technical-photo','write_error',err);return response({error:'Não foi possível salvar a foto.',code:'db_error'},503)}}
