import assert from 'node:assert/strict';
import {fresh,net,prepStats,totals,num,Entry} from '../lib/uan';
const s=fresh('2026-09-10','RT teste');s.preps=[{id:'rice',name:'Arroz',raw:10,clean:9,portion:160,cost:100,costComplete:true,closed:true,remaining:2,loss:1,note:''}];s.works=[{id:'w',name:'Obra teste',worker:10,admin:0,servedWorker:10,servedAdmin:0,vehicle:'V1',driver:'Motorista'}];
const e:Entry={id:'e',prep:'rice',work:'w',type:'GN M',quantity:2,tare:1,gross:10,temperature:80,vehicle:'V1',driver:'Motorista',operator:'RT teste',at:new Date().toISOString(),created:new Date().toISOString(),note:'',cancelled:false};s.entries=[e];
assert.equal(num('1,25'),1.25);assert.equal(num(''),null);assert.equal(num('abc'),null);assert.equal(net(e),8);assert.equal(prepStats(s,s.preps[0]).ready,10);assert.equal(prepStats(s,s.preps[0]).costKg,10);assert.equal(prepStats(s,s.preps[0]).yield,1);assert.equal(totals(s).planned,10);assert.equal(totals(s).cmv,100/109*100);assert.equal(totals(s).margin,null);
s.settings={workerPrice:10.9,adminPrice:13.5,tax:5,packaging:.1,other:2,complete:true};assert.ok(Math.abs(totals(s).margin!-.55)<1e-9);
s.preps[0].costComplete=false;assert.equal(totals(s).cmv,null);assert.equal(prepStats(s,s.preps[0]).costKg,null);s.preps[0].costComplete=true;s.preps[0].closed=false;assert.equal(prepStats(s,s.preps[0]).yield,null);
s.entries=Array.from({length:20},(_,i)=>({...e,id:String(i),temperature:i===0?80:null}));assert.equal(prepStats(s,s.preps[0]).covered,1);assert.equal(prepStats(s,s.preps[0]).due,true);s.entries.push({...e,id:'21',temperature:null});assert.equal(prepStats(s,s.preps[0]).blocks,2);assert.equal(prepStats(s,s.preps[0]).covered,1);s.entries[20].temperature=60;assert.equal(prepStats(s,s.preps[0]).covered,2);assert.equal(prepStats(s,s.preps[0]).below,1);assert.equal(prepStats(s,s.preps[0]).mean,70);s.entries[0].cancelled=true;assert.equal(prepStats(s,s.preps[0]).temps.length,1);assert.equal(prepStats(s,s.preps[0]).mean,60);s.works[0].servedAdmin=null;assert.equal(totals(s).actualRevenue,null);assert.equal(totals(s).cmv,null);console.log('PASS: decimal input, grouped tare, yield, complete costs, margin, 20-record coverage, 60°C alert, cancellations and missing counts');
// Optional meal planning must remain unknown and not block weight aggregation.
s.works[0].worker=null;s.works[0].admin=null;assert.equal(totals(s).planned,null);assert.equal(totals(s).revenue,null);assert.equal(totals(s).projected,null);assert.ok(totals(s).weight>0);s.works[0].worker=0;s.works[0].admin=0;assert.equal(totals(s).planned,0);assert.equal(totals(s).revenue,0);
const {dispatchSummary}=await import('../lib/uan');s.entries[20].route='Centro';const dispatched=dispatchSummary(s);assert.equal(dispatched[0].kg,totals(s).weight);assert.equal(dispatched[0].byPrep[0].kg,totals(s).weight);assert.ok(dispatched[0].transport.some(v=>v.includes('Centro')));console.log('PASS: optional forecasts, explicit zero, per-work weights, routes and cancelled entries');
const {routeDispatch,utensilTypes,containerBreakdown,entryTime}=await import('../lib/uan');
const grouped=fresh('2026-09-11','RT');grouped.preps=[{...s.preps[0],id:'a',name:'Arroz'},{...s.preps[0],id:'b',name:'Arroz'}];grouped.works=[{...s.works[0],id:'w1',name:'Obra A'},{...s.works[0],id:'w2',name:'Obra B'}];grouped.taras['Caixa azul']=.5;grouped.entries=[{...e,id:'1',prep:'a',work:'w1',type:'GN PP',quantity:1,tare:1,gross:6,route:'Centro',cancelled:false},{...e,id:'2',prep:'b',work:'w1',type:'Marmita',quantity:2,tare:.1,gross:1.2,route:' centro ',diet:'restritiva',dietNote:'Sem lactose',cancelled:false},{...e,id:'3',prep:'a',work:'w2',route:'Centro',cancelled:false},{...e,id:'4',prep:'a',work:'w1',route:'Norte',cancelled:false},{...e,id:'5',prep:'a',work:'w1',route:'Centro',cancelled:true}];
const gs=routeDispatch(grouped);assert.equal(gs.length,3);const ga=gs.find(g=>g.work.id==='w1'&&g.route==='Centro')!;assert.equal(ga.lines.length,2);assert.equal(ga.kg,6);assert.equal(ga.entries.length,2);assert.equal(gs.reduce((a,g)=>a+g.kg,0),totals(grouped).weight);assert.ok(containerBreakdown(ga.entries).some(c=>c.label==='Marmitas'));assert.ok(utensilTypes(grouped).includes('GN PP'));assert.ok(utensilTypes(grouped).includes('Cuba branca extra P'));assert.ok(utensilTypes(grouped).includes('Caixa azul'));assert.ok(entryTime({...e,at:'2026-09-11T12:00:00Z',deviceOffset:180}).includes('09:00:00'));assert.ok(entryTime({...e,at:'2026-09-11T12:00:00Z',deviceOffset:-120}).includes('14:00:00'));console.log('PASS: grouping across utensils and duplicate preparation names; route/work separation; unified lunchbox group; custom utensils; device clock offset');
const {destinationItems}=await import('../lib/uan');const list1=destinationItems(grouped,routeDispatch(grouped).find(g=>g.work.id==='w1'&&g.route==='Centro')!);assert.ok(list1.some(i=>i.text==='1 GN PP de Arroz'));assert.ok(list1.some(i=>i.text==='2 Marmitas (2 especiais)'));const reverse={...grouped,entries:[...grouped.entries].reverse()};const list2=destinationItems(reverse,routeDispatch(reverse).find(g=>g.work.id==='w1'&&g.route.trim().toLowerCase()==='centro')!);assert.deepEqual(list1.map(i=>i.text).sort(),list2.map(i=>i.text).sort());console.log('PASS: container manifests and insertion-order-independent destination grouping');
