import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync,writeFileSync} from 'node:fs';
import {hoursHandlers,evidenceHandlers,evidenceType} from '../lib/hours-api';
import {goalProgress,monthlyGoalProjection,hourDays,splitPeriod,hourDate,weekStart,monthSnapshot,priceCents,csvHours,personalHourSettings,personalHoursLinks,normalizeHourPhone,hourBillingDates,retroHoursAllowed,resolveBreakTimes,type HourPeriod} from '../lib/hours';
import {zipStream,bytesStream} from '../lib/hours-zip';
const p:HourPeriod={id:crypto.randomUUID(),activity:'Revisão',production:'PRUMO',start:Date.parse('2026-08-31T23:30:00-03:00'),end:Date.parse('2026-09-01T00:30:00-03:00'),rate:8000,reviewed:0};
assert.deepEqual(splitPeriod(p).map(d=>[d.date,d.seconds,d.cents]),[['2026-08-31',1800,4000],['2026-09-01',1800,4000]]);
assert.equal(priceCents(5400,8000),12000);assert.equal(hourDays([p,p],[]).length,2);assert.equal(hourDate(Date.parse('2026-09-01T02:59:00Z')),'2026-08-31');assert.equal(weekStart('2026-09-13'),'2026-09-07');
for(let rate=1;rate<120;rate++){const s=splitPeriod({...p,rate,start:Date.parse('2026-12-31T23:59:59-03:00'),end:Date.parse('2027-01-02T00:00:01-03:00')});assert.equal(s.reduce((n,d)=>n+d.cents,0),priceCents(86402,rate))}
const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');for(const file of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())readFileSync('drizzle/'+file,'utf8').split('--> statement-breakpoint').forEach(s=>{if(s.trim())sql.exec(s)});
const stmt=(q:string)=>({bind:(...args:any[])=>({first:async()=>sql.prepare(q).get(...args),all:async()=>({results:sql.prepare(q).all(...args)}),run:async()=>({meta:{changes:Number(sql.prepare(q).run(...args).changes)}}),_q:q,_args:args})});
const db={prepare:stmt,batch:async(list:any[])=>{sql.exec('BEGIN');try{const results=list.map(s=>s._q.trim().startsWith('SELECT')?{results:sql.prepare(s._q).all(...s._args)}:{meta:{changes:Number(sql.prepare(s._q).run(...s._args).changes)}});sql.exec('COMMIT');return results}catch(e){sql.exec('ROLLBACK');throw e}}};
const api=(name:string|null)=>hoursHandlers(db,async()=>name?{userId:name,email:name+'@test.com'}:null),a=api('a'),b=api('b');
const request=(body:unknown,extra:Record<string,string>={})=>new Request('https://prumo.test/api/hours',{method:'POST',headers:{'Content-Type':'application/json','X-Prumo-Request':'1',Origin:'https://prumo.test',...extra},body:JSON.stringify(body)});
let checks=126;async function status(promise:Promise<Response>,expected:number){const r=await promise;assert.equal(r.status,expected,await r.clone().text());checks++;return r}
await status(api(null).GET(),401);await status(a.POST(request({action:'settings'}, {Origin:'https://evil.test'})),403);
const settings={rate:8000,name:'Profissional',company:'Empresa',email:'empresa@test.com'};
await status(a.POST(request({action:'settings',settings})),200);await status(a.POST(request({action:'settings',settings:{...settings,rate:-1}})),400);
const id=crypto.randomUUID();await status(a.POST(request({action:'start',id,activity:'Atividade real',production:''})),200);await status(a.POST(request({action:'start',id:crypto.randomUUID(),activity:'Não duplicar',production:''})),409);assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM hour_periods').get()!.n,1);checks++;
await status(a.POST(request({action:'start',id,activity:'Atividade real',production:''})),200);await status(b.POST(request({action:'stop',id})),404);const bs:any=await(await b.GET()).json();assert.equal(bs.periods.length,0);checks++;
await status(a.POST(request({action:'settings',settings:{...settings,rate:10000}})),200);assert.equal(sql.prepare('SELECT rate FROM hour_periods WHERE id=?').get(id)!.rate,8000);checks++;
await status(a.POST(request({action:'pause',id})),200);await status(a.POST(request({action:'stop',id})),409);sql.prepare('UPDATE hour_active SET pause=pause-180000 WHERE period=?').run(id);await status(a.POST(request({action:'resume',id})),200);sql.prepare('UPDATE hour_active SET resume=resume-120000 WHERE period=?').run(id);const activeState:any=await(await a.GET()).json(),activePeriod=activeState.periods.find((period:any)=>period.id===id);assert.ok(activePeriod.pause);assert.ok(activePeriod.resume>activePeriod.pause);checks+=2;
sql.prepare('UPDATE hour_periods SET start=start-5400000 WHERE id=?').run(id);await status(a.POST(request({action:'stop',id})),200);const ended=sql.prepare('SELECT end FROM hour_periods WHERE id=?').get(id)!.end,storedBreak=sql.prepare('SELECT at,pause,resume FROM hour_manual WHERE period=?').get(id)!;assert.equal(storedBreak.at,0);assert.ok(Number(storedBreak.resume)>Number(storedBreak.pause));await status(a.POST(request({action:'stop',id})),200);assert.equal(sql.prepare('SELECT end FROM hour_periods WHERE id=?').get(id)!.end,ended);checks+=3;
sql.prepare('INSERT INTO hour_periods VALUES(?,?,?,?,?,?,?,?)').run(p.id,'a@test.com',p.activity,p.production,p.start,p.end,p.rate,0);
assert.equal(hourDays([p],[])[0].pending,0);checks++;
const objects=new Map<string,{bytes:Uint8Array}>();const bucket:any={put:async(key:string,bytes:Uint8Array)=>{objects.set(key,{bytes})},delete:async(key:string)=>{objects.delete(key)},get:async(key:string)=>objects.has(key)?{body:bytesStream(objects.get(key)!.bytes)}:null};
const evidence=(owner:string)=>evidenceHandlers(db,bucket,async()=>({userId:owner,email:owner+'@test.com'}));const upload=(period:string,name='prova.pdf',bytes=new TextEncoder().encode('%PDF-1.7\nprova de teste'))=>new Request('https://prumo.test/api/hours/evidence?period='+period+'&name='+name,{method:'POST',headers:{'Content-Type':'application/octet-stream','X-Prumo-Request':'1',Origin:'https://prumo.test'},body:bytes as any});
await status(evidence('b').POST(upload(p.id)),404);await status(evidence('a').POST(upload(p.id)),200);await status(evidence('a').POST(upload(p.id)),200);assert.equal(objects.size,1);checks++;await status(evidence('a').POST(upload(p.id,'falso.png')),400);assert.equal(evidenceType('macro.xlsm',new Uint8Array([80,75,3,4])),null);checks++;
const f=sql.prepare('SELECT id FROM hour_evidence WHERE period=?').get(p.id)!;await status(evidence('b').GET(new Request('https://prumo.test/api/hours/evidence?id='+f.id)),404);await status(evidence('a').GET(new Request('https://prumo.test/api/hours/evidence?id='+f.id)),200);
await status(a.POST(request({action:'close',month:'2026-08'})),200);await status(a.POST(request({action:'close',month:'2026-08'})),409);await status(evidence('a').POST(upload(p.id,'nova.pdf',new TextEncoder().encode('%PDF-1.7 outra'))),409);assert.equal(objects.size,1);checks++;await status(a.POST(request({action:'review',id:p.id})),409);
const snapshot=JSON.parse(String(sql.prepare('SELECT data FROM hour_archives').get()!.data));await status(a.POST(request({action:'settings',settings:{...settings,rate:11000}})),200);assert.equal(snapshot.periods[0].rate,8000);assert.equal(snapshot.days[0].cents,4000);checks+=2;const state:any=await(await a.GET()).json();const report=monthSnapshot(state,'2026-08');assert.ok(csvHours({...report,periods:[{...p,activity:'=HYPERLINK("malicioso")'}]}).includes("'="));checks++;
const personal={email:'pessoal@example.test',phone:'5579991234567'};const legacy=personalHourSettings({...settings,email:'empresa@example.test'},personal);assert.equal(legacy.email,personal.email);assert.equal(legacy.rate,settings.rate);assert.equal(legacy.phone,personal.phone);assert.equal(normalizeHourPhone('(79) 99123-4567'),personal.phone);checks+=4;
assert.equal(personalHourSettings({...settings,email:'novo@example.test',personal:true,phone:''},personal).email,'novo@example.test');checks++;
const links=personalHoursLinks(report,personal);assert.ok(links.email.startsWith('mailto:pessoal%40example.test'));assert.ok(links.whatsapp.startsWith('https://wa.me/5579991234567?text='));assert.ok(!links.email.includes('empresa%40example.test'));checks+=3;
await status(a.POST(request({action:'settings',settings:{...settings,company:'',phone:personal.phone}})),200);await status(a.POST(request({action:'settings',settings:{...settings,phone:123}})),400);
const july=crypto.randomUUID();sql.prepare('INSERT INTO hour_periods VALUES(?,?,?,?,?,?,?,?)').run(july,'a@test.com','Controle pessoal','',Date.parse('2026-07-01T09:00:00-03:00'),Date.parse('2026-07-01T10:00:00-03:00'),8000,0);sql.prepare('INSERT INTO hour_evidence VALUES(?,?,?,?,?,?,?,?)').run(crypto.randomUUID(),'a@test.com',july,'private/key','prova.pdf',20,'hash','2026-07-01');await status(a.POST(request({action:'close',month:'2026-07'})),200);
await status(a.POST(request({action:'correct',id:p.id,oldEnd:p.end,end:p.end!-1000,reason:'Esqueci de encerrar'})),409);
const old=sql.prepare('SELECT start,end FROM hour_periods WHERE id=?').get(id)!;await status(a.POST(request({action:'correct',id,oldEnd:old.end,end:Number(old.end)-60000,reason:'Intervalo sem trabalho'})),200);assert.equal(sql.prepare('SELECT old_end FROM hour_revisions WHERE period=?').get(id)!.old_end,old.end);checks++;await status(a.POST(request({action:'correct',id,oldEnd:old.end,end:Number(old.end)-90000,reason:'Edição de outra aba'})),409);await status(a.POST(request({action:'correct',id,oldEnd:Number(old.end)-60000,end:Date.now()+100000,reason:'Horário futuro inválido'})),400);
async function* files(){yield {name:'relatório.txt',stream:bytesStream(new TextEncoder().encode('Olá PRUMO'))};yield {name:'comprovantes/prova.pdf',stream:bytesStream(new TextEncoder().encode('%PDF-test'))}}
assert.equal(hourDate(hourBillingDates('2026-09').close),'2026-10-05');assert.equal(hourDate(hourBillingDates('2026-09').payment),'2026-10-10');assert.equal(hourDate(hourBillingDates('2026-12').close),'2027-01-05');checks+=3;
const clock=Date.now;const simulated=Date.parse('2026-09-15T12:00:00-03:00');Date.now=()=>simulated;
try{const retro=api('retro'),start=Date.parse('2026-09-02T08:00:00-03:00'),end=start+5400000,rid=crypto.randomUUID();const body={action:'retro',id:rid,activity:'Atividade anterior real',production:'Documento',start,end,rate:8000};
await status(retro.POST(request(body)),200);await status(retro.POST(request(body)),200);await status(retro.POST(request({...body,id:crypto.randomUUID(),start:start+1000})),409);
const rs:any=await(await retro.GET()).json();assert.equal(rs.periods.length,1);assert.equal(rs.periods[0].manual_at,simulated);assert.equal(hourDays(rs.periods,rs.evidence)[0].cents,12000);assert.equal(hourDays(rs.periods,rs.evidence)[0].date,'2026-09-02');assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM hour_active WHERE owner=?').get('retro@test.com')!.n,0);checks+=5;
await status(retro.POST(request({...body,id:crypto.randomUUID(),start:Date.parse('2026-08-31T08:00:00-03:00'),end:Date.parse('2026-08-31T09:00:00-03:00')})),400);await status(retro.POST(request({...body,id:crypto.randomUUID(),start:simulated-100000,end:simulated-1000})),400);await status(retro.POST(request({...body,id:crypto.randomUUID(),end:simulated+1000})),400);await status(retro.POST(request({...body,id:crypto.randomUUID(),end:start})),400);
const overnight={...body,id:crypto.randomUUID(),start:Date.parse('2026-09-03T23:30:00-03:00'),end:Date.parse('2026-09-04T00:30:00-03:00')};await status(retro.POST(request(overnight)),200);assert.deepEqual(splitPeriod(overnight as any).map(d=>d.seconds),[1800,1800]);checks++;
assert.equal(retroHoursAllowed(start,end,Date.parse('2026-09-01T10:00:00-03:00')),false);checks++;
// Reusing an existing timer ID must never relabel it as retroactive.
const timerId=crypto.randomUUID();await status(retro.POST(request({action:'settings',settings})),200);await status(retro.POST(request({action:'start',id:timerId,activity:'Timer',production:''})),200);await status(retro.POST(request({...body,id:timerId,start:start+86400000,end:end+86400000})),409);assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM hour_manual WHERE period=?').get(timerId)!.n,0);checks++;
const on5=hourBillingDates('2026-06').close;sql.prepare('INSERT INTO hour_periods VALUES(?,?,?,?,?,?,?,?)').run(crypto.randomUUID(),'billing@test.com','Trabalho junho','',Date.parse('2026-06-10T08:00:00-03:00'),Date.parse('2026-06-10T09:00:00-03:00'),8000,0);const bp=sql.prepare('SELECT id FROM hour_periods WHERE owner=?').get('billing@test.com')!;sql.prepare('INSERT INTO hour_evidence VALUES(?,?,?,?,?,?,?,?)').run(crypto.randomUUID(),'billing@test.com',bp.id,'private/billing','prova.pdf',20,'hash','2026-06-10');await status(api('billing').POST(request({action:'settings',settings:{...settings,company:''}})),200);
Date.now=()=>on5-1000;await status(api('billing').POST(request({action:'close',month:'2026-06'})),400);Date.now=()=>on5;await status(api('billing').POST(request({action:'close',month:'2026-06'})),200);
}finally{Date.now=clock}

const daily=api('daily'),dailyStart=Date.parse('2026-09-01T08:00:00-03:00'),dailyBody={action:'day',month:'2026-09',id:crypto.randomUUID(),start:dailyStart,pause:dailyStart+4*3600000,resume:dailyStart+5*3600000,end:dailyStart+9*3600000,activity:'Conferência em andamento',result:'',production:'',rate:8000};
await status(daily.POST(request(dailyBody)),200);await status(daily.POST(request(dailyBody)),200);const ds:any=await(await daily.GET()).json();assert.equal(hourDays(ds.periods,[])[0].seconds,8*3600);assert.equal(hourDays(ds.periods,[])[0].cents,64000);assert.equal(ds.periods[0].pause,dailyBody.pause);checks+=3;
await status(daily.POST(request({...dailyBody,id:crypto.randomUUID(),pause:null})),400);await status(daily.POST(request({...dailyBody,id:crypto.randomUUID(),resume:dailyBody.pause-1000})),400);await status(daily.POST(request({...dailyBody,id:crypto.randomUUID(),month:'2026-08'})),400);await status(daily.POST(request({...dailyBody,id:crypto.randomUUID()})),409);
await status(daily.POST(request({action:'correct',id:dailyBody.id,oldEnd:dailyBody.end,end:dailyBody.resume-1000,reason:'Fim anterior ao retorno'})),400);
const second={...dailyBody,id:crypto.randomUUID(),start:dailyStart+86400000,end:dailyStart+86400000+9*3600000,pause:null,resume:null,result:'Documento revisado'};await status(daily.POST(request(second)),200);const ds2:any=await(await daily.GET()).json();assert.equal(hourDays(ds2.periods,[]).find(d=>d.date==='2026-09-02')!.seconds,9*3600);assert.equal(ds2.periods.find((p:any)=>p.id===second.id).result,'Documento revisado');checks+=2;
await status(daily.POST(request({action:'goal',month:'2026-09',cents:200000})),200);await status(daily.POST(request({action:'goal',month:'2026-09',cents:-1})),400);const goalState:any=await(await daily.GET()).json();assert.equal(monthSnapshot(goalState,'2026-09').goal,200000);assert.equal(monthSnapshot(await(await b.GET()).json(),'2026-09').goal,0);assert.deepEqual(goalProgress(250000,200000),{percent:125,remaining:0,excess:50000});checks+=3;
assert.deepEqual(monthlyGoalProjection(80000,200000,8000,'2026-09',Date.parse('2026-09-25T12:00:00-03:00')),{remaining:120000,hoursSeconds:54000,daysRemaining:6,dailySeconds:9000});checks++;
await status(a.POST(request({action:'goal',month:'2026-07',cents:200000})),409);
const previous={...dailyBody,id:crypto.randomUUID(),month:'2026-06',start:Date.parse('2026-06-01T08:00:00-03:00'),end:Date.parse('2026-06-01T09:00:00-03:00'),pause:null,resume:null};await status(daily.POST(request(previous)),200);
const breakMidnight={...p,start:Date.parse('2026-08-31T22:00:00-03:00'),pause:Date.parse('2026-08-31T23:00:00-03:00'),resume:Date.parse('2026-09-01T01:00:00-03:00'),end:Date.parse('2026-09-01T02:00:00-03:00')};assert.deepEqual(splitPeriod(breakMidnight).map(d=>d.seconds),[3600,3600]);checks++;
const rawOvernightBreak=resolveBreakTimes(Date.parse('2026-09-10T22:00:00-03:00'),Date.parse('2026-09-11T06:00:00-03:00'),Date.parse('2026-09-10T00:30:00-03:00'),Date.parse('2026-09-10T01:00:00-03:00'));assert.equal(rawOvernightBreak.valid,true);assert.equal(rawOvernightBreak.pause,Date.parse('2026-09-11T00:30:00-03:00'));assert.equal(rawOvernightBreak.resume,Date.parse('2026-09-11T01:00:00-03:00'));checks+=3;
const overnightDraft={...dailyBody,id:crypto.randomUUID(),start:Date.parse('2026-09-10T22:00:00-03:00'),end:Date.parse('2026-09-11T06:00:00-03:00'),pause:Date.parse('2026-09-10T00:30:00-03:00'),resume:Date.parse('2026-09-10T01:00:00-03:00')};await status(daily.POST(request(overnightDraft)),200);const overnightState:any=await(await daily.GET()).json(),storedOvernight=overnightState.periods.find((period:any)=>period.id===overnightDraft.id);assert.equal(storedOvernight.pause,Date.parse('2026-09-11T00:30:00-03:00'));assert.equal(storedOvernight.resume,Date.parse('2026-09-11T01:00:00-03:00'));checks+=2;
const example={action:'day',month:'2026-09',id:crypto.randomUUID(),start:Date.parse('2026-09-09T09:00:00-03:00'),pause:Date.parse('2026-09-09T12:30:00-03:00'),resume:Date.parse('2026-09-09T14:00:00-03:00'),end:Date.parse('2026-09-09T17:30:00-03:00'),activity:'Revisão de cardápio e adequação de per capita',production:'',result:'',rate:8000};await status(daily.POST(request(example)),200);const exampleState:any=await(await daily.GET()).json(),examplePeriod=exampleState.periods.find((p:any)=>p.id===example.id);assert.equal(examplePeriod.activity,example.activity);assert.equal(hourDays([examplePeriod],[])[0].date,'2026-09-09');assert.equal(hourDays([examplePeriod],[])[0].seconds,7*3600);assert.equal(hourDays([examplePeriod],[])[0].cents,56000);checks+=4;

const multiApi=api('multi'),multiDay={...example,id:crypto.randomUUID(),activity:'Revisão de cardápio\nAdequação de per capita'};await status(multiApi.POST(request(multiDay)),200);const afternoon={...multiDay,id:crypto.randomUUID(),start:multiDay.end,end:multiDay.end+3600000,pause:null,resume:null,activity:'Planejamento da próxima revisão'};await status(multiApi.POST(request(afternoon)),200);const multiState:any=await(await multiApi.GET()).json();assert.equal(multiState.periods.length,2);assert.equal(hourDays(multiState.periods,[]).length,1);assert.equal(hourDays(multiState.periods,[])[0].seconds,8*3600);assert.equal(hourDays(multiState.periods,[])[0].pending,0);checks+=4;
const multiClock=Date.now;try{Date.now=()=>Date.parse('2026-10-05T10:00:00-03:00');await status(multiApi.POST(request({action:'settings',settings:{...settings,company:''}})),200);await status(multiApi.POST(request({action:'close',month:'2026-09'})),200);const preserved:any=await(await multiApi.GET()).json();assert.equal(preserved.periods.length,2);assert.equal(preserved.evidence.length,0);assert.equal(JSON.parse(preserved.archives[0].data).periods[0].activity,afternoon.activity);checks+=3;}finally{Date.now=multiClock}
writeFileSync('.sites-runtime/hours-test.zip',new Uint8Array(await new Response(zipStream(files())).arrayBuffer()));checks++;
console.log(checks+' verificações de horas e segurança passaram. ZIP de teste gerado para validação independente.');
