import {jsPDF} from 'jspdf';
import autoTable from 'jspdf-autotable';
import {normal,bold} from './pdf-font';
import {GSI_BLACK,GSI_RED,GSI_STATIONERY} from './gsi-brand';
import {durationText,hoursMoney,splitPeriod,type monthSnapshot} from './hours';
export function makeHoursReport(s:ReturnType<typeof monthSnapshot>,closedAt?:string){
 const doc=new jsPDF();doc.addFileToVFS('Prumo.ttf',normal);doc.addFont('Prumo.ttf','Prumo','normal');doc.addFileToVFS('PrumoBold.ttf',bold);doc.addFont('PrumoBold.ttf','Prumo','bold');doc.setFont('Prumo');let y=52;
 const newPage=()=>{doc.addPage();y=52};const text=(value:string,size=10,color='#1c1c1c')=>{doc.setFontSize(size);doc.setTextColor(color);const lines=doc.splitTextToSize(value,180);if(y+lines.length*size*.45>252)newPage();doc.text(lines,14,y);y+=lines.length*size*.45+5};
 const table=(head:string[],body:string[][])=>{autoTable(doc,{startY:y,head:[head],body,rowPageBreak:'avoid',margin:{left:14,right:14,top:52,bottom:42},styles:{font:'Prumo',fontSize:8,cellPadding:3,textColor:GSI_BLACK},headStyles:{fillColor:GSI_RED,textColor:[255,255,255]},alternateRowStyles:{fillColor:[255,249,219]}});y=(doc as any).lastAutoTable.finalY+10};
 const at=(ms:number)=>new Date(ms).toLocaleString('pt-BR',{timeZone:s.zone});text('CONTROLE PESSOAL DE HORAS',16,'#e20023');text('PRUMO SYSTEM | '+s.month.split('-').reverse().join('/')+' | '+s.zone+' (UTC-3)');text('Profissional: '+(s.settings.name||'Não informado')+(s.settings.company?' | Vínculo: '+s.settings.company:''));text(closedAt?'Relatório mensal arquivado':'Relatório de conferência');
 const seconds=s.days.reduce((n,d)=>n+d.seconds,0),cents=s.days.reduce((n,d)=>n+d.cents,0);text(s.days.length+' dias trabalhados | '+durationText(seconds)+' | Valor bruto: '+hoursMoney(cents),12,'#e20023');table(['Dia trabalhado','Horas (h:m:s)','Valor'],s.days.map(d=>[d.date.split('-').reverse().join('/'),durationText(d.seconds),hoursMoney(d.cents)]));
 if(s.goal)text('Meta mensal: '+hoursMoney(s.goal)+' | Acumulado: '+hoursMoney(cents)+' | Falta: '+hoursMoney(Math.max(0,s.goal-cents)));text('Atividades e horários trabalhados',12,'#e20023');table(['Atividades / resultado','Horários (Bahia)','Horas no mês / valor hora','Subtotal no mês'],s.periods.map(p=>{const parts=splitPeriod(p).filter(d=>d.date.startsWith(s.month));return [p.activity+(p.result?'\nResultado: '+p.result:'')+(p.production?'\nPRUMO: '+p.production:''),'Início: '+at(p.start)+(p.pause!=null&&p.resume!=null?'\nPausa: '+at(p.pause)+'\nRetorno: '+at(p.resume):'')+'\nFinalização: '+at(p.end!),durationText(parts.reduce((n,d)=>n+d.seconds,0))+'\n'+hoursMoney(p.rate)+'/h',hoursMoney(parts.reduce((n,d)=>n+d.cents,0))]}));text('Pausas declaradas são descontadas das horas efetivas. Somente períodos encerrados são contabilizados. O valor da hora é preservado por período.',8,'#555555');
 for(let i=1;i<=doc.getNumberOfPages();i++){doc.setPage(i);doc.addImage(GSI_STATIONERY,'PNG',0,0,210,297,undefined,'FAST');doc.setFontSize(8);doc.setTextColor(...GSI_RED);doc.text('PRUMO SYSTEM | '+s.month,14,286);doc.setTextColor(...GSI_BLACK);doc.text(i+'/'+doc.getNumberOfPages(),188,286)}return doc;
}
