export const HOURS_ZONE='America/Bahia';
export type HourSettings={rate:number;name:string;company:string;email:string;phone?:string;personal?:boolean};
export type Evidence={id:string;period:string;name:string;size:number;hash:string;at:string};
export type HourPeriod={id:string;activity:string;production:string;start:number;end:number|null;rate:number;reviewed:number;manual_at?:number|null;pause?:number|null;resume?:number|null;result?:string};
export type HourDay={date:string;seconds:number;cents:number;pending:number};
export type HourArchive={id:string;month:string;at:string;data:string};
export type HourRevision={id:string;period:string;old_end:number;new_end:number;reason:string;at:number};
export type HoursState={settings:HourSettings;periods:HourPeriod[];evidence:Evidence[];archives:HourArchive[];revisions:HourRevision[];serverNow:number;goals?:{month:string;cents:number}[]};
export const defaultHourSettings:HourSettings={rate:0,name:'',company:'',email:'',phone:'',personal:false};
export type HourContacts={email:string;phone:string};
export function personalHourSettings(settings:HourSettings,contacts:HourContacts):HourSettings{return {...settings,email:settings.personal?settings.email:contacts.email,phone:settings.personal?(settings.phone??contacts.phone):contacts.phone,personal:true}}
export function normalizeHourPhone(value:string){const digits=value.replace(/\D/g,'');return digits.length===10||digits.length===11?'55'+digits:digits}
export function personalHoursSummary(s:ReturnType<typeof monthSnapshot>){return ['PRUMO — Meu controle pessoal de horas',s.month.split('-').reverse().join('/'),s.settings.name,'Dias trabalhados: '+s.days.length,'Horas: '+durationText(s.days.reduce((n,d)=>n+d.seconds,0)),'Valor bruto: '+hoursMoney(s.days.reduce((n,d)=>n+d.cents,0)),...s.days.map(d=>d.date.split('-').reverse().join('/')+' · '+durationText(d.seconds)+' · '+hoursMoney(d.cents)),'Atividades: '+s.periods.slice(0,12).map(p=>p.activity).join('; '),s.periods.length>12?'Demais atividades no relatório PDF.':'','Relatório PDF disponível no meu acesso privado ao PRUMO.'].filter(Boolean).join('\n')}
export function personalHoursLinks(s:ReturnType<typeof monthSnapshot>,contacts:HourContacts){const text=personalHoursSummary(s),phone=normalizeHourPhone(contacts.phone);return {email:contacts.email?'mailto:'+encodeURIComponent(contacts.email)+'?subject='+encodeURIComponent('Meu controle de horas — '+s.month)+'&body='+encodeURIComponent(text):'',whatsapp:/^\d{10,15}$/.test(phone)?'https://wa.me/'+phone+'?text='+encodeURIComponent(text):''}}
// A fixed UTC-3 accounting calendar matches America/Bahia (no DST).
const offset=3*3600*1000;
export function hourDate(ms:number){return new Date(ms-offset).toISOString().slice(0,10)}
export function monthBounds(month:string){const [y,m]=month.split('-').map(Number);return [Date.UTC(y,m-1,1)+offset,Date.UTC(y,m,1)+offset]}
export function hourBillingDates(month:string){const [,next]=monthBounds(month);return {close:next+4*86400000,payment:next+9*86400000}}
export function retroHoursAllowed(start:number,end:number,now:number){const date=hourDate(now),[monthStart]=monthBounds(date.slice(0,7)),today=Date.parse(date+'T00:00:00-03:00');return Number.isSafeInteger(start)&&Number.isSafeInteger(end)&&start%1000===0&&end%1000===0&&start>=monthStart&&start<today&&end>start&&end<=now}
export function weekStart(date:string){const d=new Date(date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-(d.getUTCDay()+6)%7);return d.toISOString().slice(0,10)}
export function durationText(seconds:number){const s=Math.max(0,Math.floor(seconds));return `${Math.floor(s/3600).toString().padStart(2,'0')}:${Math.floor(s/60)%60<10?'0':''}${Math.floor(s/60)%60}:${(s%60).toString().padStart(2,'0')}`}
export const hoursMoney=(cents:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(cents/100);
export function priceCents(seconds:number,rate:number){return Number((BigInt(Math.floor(seconds))*BigInt(rate)+BigInt(1800))/BigInt(3600))}
export function effectiveSeconds(p:HourPeriod){return p.end===null?0:Math.max(0,(p.end-p.start-(p.pause!=null&&p.resume!=null?p.resume-p.pause:0))/1000)}
export function resolveBreakTimes(start:number,end:number,pause:number|null,resume:number|null){if(pause===null&&resume===null)return{pause:null,resume:null,valid:true};if(pause===null||resume===null||!Number.isFinite(start)||!Number.isFinite(end)||!Number.isFinite(pause)||!Number.isFinite(resume))return{pause,resume,valid:false};let resolvedPause=pause,resolvedResume=resume;if(resolvedPause<=start)resolvedPause+=86400000;if(resolvedResume<=resolvedPause)resolvedResume+=86400000;return{pause:resolvedPause,resume:resolvedResume,valid:resolvedPause>start&&resolvedResume>resolvedPause&&resolvedResume<end}}
export function goalProgress(earned:number,goal:number){return {percent:goal>0?earned/goal*100:0,remaining:Math.max(0,goal-earned),excess:Math.max(0,earned-goal)}}
export function monthlyGoalProjection(earned:number,goal:number,rate:number,month:string,now:number){const remaining=Math.max(0,goal-earned),hoursSeconds=remaining>0&&rate>0?Math.ceil(remaining*3600/rate):0,[year,monthNumber]=month.split('-').map(Number),current=hourDate(now),currentMonth=current.slice(0,7),daysInMonth=new Date(Date.UTC(year,monthNumber,0)).getUTCDate(),daysRemaining=month<currentMonth?0:month>currentMonth?daysInMonth:Math.max(0,daysInMonth-Number(current.slice(8))+1),dailySeconds=hoursSeconds>0&&daysRemaining>0?Math.ceil(hoursSeconds/daysRemaining):0;return {remaining,hoursSeconds,daysRemaining,dailySeconds}}
export function splitPeriod(p:HourPeriod){if(p.end===null||p.end<=p.start)return [];const days:{date:string;seconds:number;cents:number}[]=[];let elapsed=0,allocated=0;
 const intervals=p.pause!=null&&p.resume!=null?[[p.start,p.pause],[p.resume,p.end]]:[[p.start,p.end]];
 for(const [from,to] of intervals){let cursor=from;while(cursor<to){const date=hourDate(cursor),midnight=Date.parse(date+'T00:00:00Z')+offset+86400000,until=Math.min(to,midnight),seconds=Math.floor((until-cursor)/1000);elapsed+=seconds;const cumulative=priceCents(elapsed,p.rate);days.push({date,seconds,cents:cumulative-allocated});allocated=cumulative;cursor=until;}}return days;
}
export function hourDays(periods:HourPeriod[],evidence:Evidence[]){const map=new Map<string,HourDay>();for(const p of periods)for(const segment of splitPeriod(p)){const row=map.get(segment.date)??{date:segment.date,seconds:0,cents:0,pending:0};row.seconds+=segment.seconds;row.cents+=segment.cents;if(!p.reviewed&&effectiveSeconds(p)>16*3600)row.pending+=segment.seconds;map.set(row.date,row)}return [...map.values()].filter(d=>d.seconds>0).sort((a,b)=>a.date.localeCompare(b.date))}
export function monthSnapshot(state:HoursState,month:string){const [start,end]=monthBounds(month);const periods=state.periods.filter(p=>p.end!==null&&p.start<end&&p.end>start);return {month,goal:state.goals?.find(g=>g.month===month)?.cents??0,billing:hourBillingDates(month),zone:HOURS_ZONE,settings:state.settings,periods,evidence:state.evidence.filter(e=>periods.some(p=>p.id===e.period)),revisions:state.revisions.filter(r=>periods.some(p=>p.id===r.period)),days:hourDays(periods,state.evidence).filter(d=>d.date.startsWith(month))}}
export function csvHours(snapshot:ReturnType<typeof monthSnapshot>){const safe=(s:unknown)=>{let v=String(s??'');if(/^[\s]*[=+@-]/.test(v))v="'"+v;return '"'+v.replaceAll('"','""')+'"'};const rows=[['Data','Início (UTC)','Fim (UTC)','Atividade','Referência PRUMO','Horas no dia','Valor hora (R$)','Subtotal no dia (R$)','Comprovantes','Tipo de registro','Lançado em (UTC)','Pausa (UTC)','Retorno (UTC)','Resultado opcional']];for(const p of snapshot.periods)for(const d of splitPeriod(p).filter(d=>d.date.startsWith(snapshot.month)))rows.push([d.date,new Date(p.start).toISOString(),new Date(p.end!).toISOString(),p.activity,p.production,(d.seconds/3600).toFixed(6).replace('.',','),(p.rate/100).toFixed(2).replace('.',','),(d.cents/100).toFixed(2).replace('.',','),snapshot.evidence.filter(e=>e.period===p.id).map(e=>e.name+' [SHA-256 '+e.hash+']').join(' | '),p.manual_at?'Retroativo declarado':'Cronômetro',p.manual_at?new Date(p.manual_at).toISOString():'',p.pause!=null?new Date(p.pause).toISOString():'',p.resume!=null?new Date(p.resume).toISOString():'',p.result??'']);return '\uFEFF'+rows.map(r=>r.map(safe).join(';')).join('\r\n')}
