import {response,mutationAllowed,type Identity} from './production-api';
import {defaultHourSettings,personalHourSettings,normalizeHourPhone,hourDate,monthBounds,monthSnapshot,hourBillingDates,retroHoursAllowed,resolveBreakTimes,type HoursState,type HourSettings,type HourContacts} from './hours';
type DB={prepare:(q:string)=>any;batch:(s:any[])=>Promise<any[]>};
const uuid=(v:unknown):v is string=>typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(v);
const ownerOf=(u:Identity)=>u.email?.trim().toLowerCase()||u.userId;
export async function hourState(db:DB,owner:string):Promise<HoursState>{const [settings,periods,evidence,archives,revisions,goals]=await db.batch([db.prepare('SELECT data FROM hour_settings WHERE owner=?').bind(owner),db.prepare('SELECT p.id,p.activity,p.production,p.start,p.end,p.rate,p.reviewed,m.at AS manual_at,m.pause,m.resume,m.result FROM hour_periods p LEFT JOIN hour_manual m ON m.period=p.id AND m.owner=p.owner WHERE p.owner=? ORDER BY p.start DESC').bind(owner),db.prepare('SELECT id,period,name,size,hash,at FROM hour_evidence WHERE owner=? ORDER BY at').bind(owner),db.prepare('SELECT id,month,at,data FROM hour_archives WHERE owner=? ORDER BY month DESC').bind(owner),db.prepare('SELECT id,period,old_end,new_end,reason,at FROM hour_revisions WHERE owner=? ORDER BY at').bind(owner),db.prepare('SELECT month,cents FROM hour_goals WHERE owner=?').bind(owner)]);return {goals:goals.results,settings:settings.results[0]?JSON.parse(settings.results[0].data):defaultHourSettings,periods:periods.results,evidence:evidence.results,archives:archives.results,revisions:revisions.results,serverNow:Math.floor(Date.now()/1000)*1000}}
async function smallJSON(req:Request){if(!req.body)throw Error('body');const reader=req.body.getReader(),chunks:Uint8Array[]=[];let size=0;while(true){const r=await reader.read();if(r.done)break;size+=r.value.byteLength;if(size>20000){await reader.cancel();throw Error('size')}chunks.push(r.value)}const bytes=new Uint8Array(size);let pos=0;for(const c of chunks){bytes.set(c,pos);pos+=c.length}return JSON.parse(new TextDecoder().decode(bytes))}
export function hoursHandlers(db:DB,getUser:()=>Promise<Identity|null>,contacts:HourContacts={email:'',phone:''}){return {
 GET:async()=>{try{const u=await getUser();if(!u)return response({error:'Entre com sua conta para acessar suas horas.'},401);const state=await hourState(db,ownerOf(u));state.settings=personalHourSettings(state.settings,contacts);return response(state)}catch{return response({error:'Não foi possível carregar suas horas. Tente novamente.'},503)}},
 POST:async(req:Request)=>{try{const u=await getUser();if(!u)return response({error:'Entre com sua conta para registrar horas.'},401);if(!mutationAllowed(req))return response({error:'Solicitação não permitida.'},403);let b:any;try{b=await smallJSON(req)}catch{return response({error:'Dados inválidos ou muito extensos.'},400)}if(!b||typeof b!=='object'||Array.isArray(b))return response({error:'Dados inválidos.'},400);const owner=ownerOf(u),now=Math.floor(Date.now()/1000)*1000;
 if(b.action==='settings'){const s=b.settings as HourSettings;if(!s||!Number.isSafeInteger(s.rate)||s.rate<=0||s.rate>100000000||typeof s.name!=='string'||s.name.length>120||typeof s.company!=='string'||s.company.length>120||typeof s.email!=='string'||s.email.length>200||(s.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s.email)))return response({error:'Confira o valor da hora e a identificação.'},400);if(s.phone!==undefined&&typeof s.phone!=='string')return response({error:'Confira seu WhatsApp com DDD.'},400);const phone=normalizeHourPhone(s.phone??'');if(phone&&!/^\d{10,15}$/.test(phone))return response({error:'Confira seu WhatsApp com DDD.'},400);const clean={rate:s.rate,name:s.name.trim(),company:s.company.trim(),email:s.email.trim(),phone,personal:true};await db.prepare('INSERT INTO hour_settings(owner,data) VALUES(?,?) ON CONFLICT(owner) DO UPDATE SET data=excluded.data').bind(owner,JSON.stringify(clean)).run();return response({ok:true})}

 if(b.action==='goal'){if(typeof b.month!=='string'||!/^20\d{2}-(0[1-9]|1[0-2])$/.test(b.month)||!Number.isSafeInteger(b.cents)||b.cents<0||b.cents>10000000000)return response({error:'Informe um teto mensal válido.'},400);const r=await db.prepare('INSERT INTO hour_goals(owner,month,cents) SELECT ?,?,? WHERE NOT EXISTS(SELECT 1 FROM hour_archives WHERE owner=? AND month=?) ON CONFLICT(owner,month) DO UPDATE SET cents=excluded.cents').bind(owner,b.month,b.cents,owner,b.month).run();return r.meta.changes?response({ok:true}):response({error:'O mês arquivado preserva o teto do fechamento.'},409)}
 if(b.action==='day'){if(!uuid(b.id)||typeof b.month!=='string'||!/^20\d{2}-(0[1-9]|1[0-2])$/.test(b.month)||typeof b.activity!=='string'||!b.activity.trim()||b.activity.length>2000||typeof b.production!=='string'||b.production.length>120||typeof b.result!=='string'||b.result.length>2000||!Number.isSafeInteger(b.rate)||b.rate<=0||b.rate>100000000)return response({error:'Confira o dia, a atividade e o valor da hora.'},400);
 const [first,last]=monthBounds(b.month),validTime=(v:any)=>Number.isSafeInteger(v)&&v%1000===0;if(!validTime(b.start)||!validTime(b.end)||b.start<first||b.start>=last||b.end>b.start+86400000||b.end<=b.start||b.end>now)return response({error:'Use um dia do mês de referência, até hoje, com horários já trabalhados e duração de até 24 horas.'},400);
 const resolvedBreak=resolveBreakTimes(b.start,b.end,b.pause??null,b.resume??null),pause=resolvedBreak.pause,resume=resolvedBreak.resume;if(!resolvedBreak.valid||pause!==null&&(!validTime(pause)||!validTime(resume)))return response({error:'Informe pausa e retorno juntos, nesta ordem: início, pausa, retorno e finalização. Deixe ambos vazios se não houve intervalo.'},400);
 const prior=await db.prepare('SELECT p.activity,p.production,p.start,p.end,p.rate,m.pause,m.resume,m.result FROM hour_periods p JOIN hour_manual m ON m.period=p.id AND m.owner=p.owner WHERE p.id=? AND p.owner=?').bind(b.id,owner).first();if(prior)return prior.activity===b.activity.trim()&&prior.production===b.production.trim()&&prior.start===b.start&&prior.end===b.end&&prior.rate===b.rate&&prior.pause===pause&&prior.resume===resume&&prior.result===b.result.trim()?response({ok:true}):response({error:'Identificador já utilizado.'},409);
 const r=await db.batch([db.prepare('INSERT OR IGNORE INTO hour_periods(id,owner,activity,production,start,end,rate,reviewed) SELECT ?,?,?,?,?,?,?,0 WHERE NOT EXISTS(SELECT 1 FROM hour_periods WHERE owner=? AND start<? AND COALESCE(end,?)>?) AND NOT EXISTS(SELECT 1 FROM hour_archives WHERE owner=? AND start<? AND end>?)').bind(b.id,owner,b.activity.trim(),b.production.trim(),b.start,b.end,b.rate,owner,b.end,now+1000,b.start,owner,b.end,b.start),db.prepare('INSERT INTO hour_manual(period,owner,at,pause,resume,result) SELECT id,owner,?,?,?,? FROM hour_periods WHERE id=? AND owner=? AND changes()=1').bind(now,pause,resume,b.result.trim(),b.id,owner)]);return r[0].meta.changes?response({ok:true}):response({error:'Há outra atividade nesse período ou o mês já está arquivado.'},409)}
 if(b.action==='retro'){if(!uuid(b.id)||typeof b.activity!=='string'||!b.activity.trim()||b.activity.length>2000||typeof b.production!=='string'||b.production.length>120||!Number.isSafeInteger(b.rate)||b.rate<=0||b.rate>100000000)return response({error:'Informe atividade, horários e valor da hora aplicado naquele dia.'},400);const prior=await db.prepare('SELECT p.activity,p.production,p.start,p.end,p.rate FROM hour_periods p JOIN hour_manual m ON m.period=p.id WHERE p.id=? AND p.owner=? AND m.owner=?').bind(b.id,owner,owner).first();if(prior)return prior.activity===b.activity.trim()&&prior.production===b.production.trim()&&prior.start===b.start&&prior.end===b.end&&prior.rate===b.rate?response({ok:true}):response({error:'Este identificador já foi utilizado. Atualize e confira seus registros.'},409);if(!retroHoursAllowed(b.start,b.end,now))return response({error:'Use um dia passado do mês vigente, com fim posterior ao início e sem horários futuros (fuso Bahia).'},400);const result=await db.batch([db.prepare(`INSERT OR IGNORE INTO hour_periods(id,owner,activity,production,start,end,rate,reviewed) SELECT ?,?,?,?,?,?,?,0 WHERE NOT EXISTS(SELECT 1 FROM hour_periods WHERE owner=? AND start<? AND COALESCE(end,?)>?) AND NOT EXISTS(SELECT 1 FROM hour_archives WHERE owner=? AND start<? AND end>?)`).bind(b.id,owner,b.activity.trim(),b.production.trim(),b.start,b.end,b.rate,owner,b.end,now+1000,b.start,owner,b.end,b.start),db.prepare('INSERT OR IGNORE INTO hour_manual(period,owner,at) SELECT id,owner,? FROM hour_periods WHERE id=? AND owner=? AND changes()=1').bind(now,b.id,owner)]);return result[0].meta.changes?response({ok:true}):response({error:'O período sobrepõe outra atividade, pertence a um mês fechado ou já foi registrado. Confira os horários.'},409)}
 if(b.action==='start'){if(!uuid(b.id)||typeof b.activity!=='string'||!b.activity.trim()||b.activity.length>2000||typeof b.production!=='string'||b.production.length>120)return response({error:'Descreva a atividade e confira a referência.'},400);const existing=await db.prepare('SELECT id,activity,production FROM hour_periods WHERE id=? AND owner=?').bind(b.id,owner).first();if(existing)return existing.activity===b.activity.trim()&&existing.production===b.production.trim()?response({ok:true}):response({error:'Identificador já utilizado.'},409);const setting=await db.prepare('SELECT data FROM hour_settings WHERE owner=?').bind(owner).first();const rate=setting?JSON.parse(setting.data).rate:0;if(!rate)return response({error:'Salve o valor da hora antes de iniciar.'},400);const closed=await db.prepare('SELECT id FROM hour_archives WHERE owner=? AND start<=? AND end>?').bind(owner,now,now).first();if(closed)return response({error:'Este mês está fechado. Não é possível iniciar novos períodos nele.'},409);try{await db.batch([db.prepare('INSERT INTO hour_periods(id,owner,activity,production,start,end,rate,reviewed) SELECT ?,?,?,?,?,NULL,?,0 WHERE NOT EXISTS(SELECT 1 FROM hour_archives WHERE owner=? AND start<=? AND end>?) AND NOT EXISTS(SELECT 1 FROM hour_periods WHERE owner=? AND end>?)').bind(b.id,owner,b.activity.trim(),b.production.trim(),now,rate,owner,now,now,owner,now),db.prepare('INSERT INTO hour_active(owner,period) VALUES(?,?)').bind(owner,b.id)])}catch{return response({error:'Já existe uma atividade em andamento, o mês foi fechado ou este início foi registrado. Atualize a página.'},409)}return response({ok:true})}
 if(b.action==='stop'){if(!uuid(b.id))return response({error:'Atividade inválida.'},400);const p=await db.prepare('SELECT start,end FROM hour_periods WHERE id=? AND owner=?').bind(b.id,owner).first();if(!p)return response({error:'Atividade não encontrada.'},404);if(p.end!==null)return response({ok:true});if(now<=p.start)return response({error:'Aguarde pelo menos um segundo antes de encerrar.'},400);await db.batch([db.prepare('UPDATE hour_periods SET end=? WHERE id=? AND owner=? AND end IS NULL').bind(now,b.id,owner),db.prepare('DELETE FROM hour_active WHERE owner=? AND period=?').bind(owner,b.id)]);return response({ok:true})}
 if(b.action==='review'){if(!uuid(b.id))return response({error:'Atividade inválida.'},400);const r=await db.prepare('UPDATE hour_periods SET reviewed=? WHERE id=? AND owner=? AND end IS NOT NULL AND NOT EXISTS(SELECT 1 FROM hour_archives a WHERE a.owner=hour_periods.owner AND a.start<hour_periods.end AND a.end>hour_periods.start)').bind(now,b.id,owner).run();return r.meta.changes?response({ok:true}):response({error:'Período não encontrado ou mês já fechado.'},409)}
 if(b.action==='correct'){if(!uuid(b.id)||!Number.isSafeInteger(b.oldEnd)||!Number.isSafeInteger(b.end)||b.end%1000!==0||b.end>now||typeof b.reason!=='string'||b.reason.trim().length<5||b.reason.length>1000)return response({error:'Informe o fim efetivo e uma justificativa de pelo menos cinco caracteres.'},400);const p=await db.prepare('SELECT p.start,p.end,m.resume FROM hour_periods p LEFT JOIN hour_manual m ON m.period=p.id AND m.owner=p.owner WHERE p.id=? AND p.owner=?').bind(b.id,owner).first();if(!p)return response({error:'Período não encontrado.'},404);if(p.end===null||b.end<=p.start||p.resume!=null&&b.end<=p.resume||b.end===p.end)return response({error:'O fim deve ser posterior ao início e diferente do horário atual.'},400);const revision=crypto.randomUUID();const result=await db.batch([db.prepare(`INSERT INTO hour_revisions(id,owner,period,old_end,new_end,reason,at) SELECT ?,owner,id,end,?,?,? FROM hour_periods p WHERE id=? AND owner=? AND end=? AND NOT EXISTS(SELECT 1 FROM hour_archives WHERE owner=? AND start<? AND end>p.start) AND NOT EXISTS(SELECT 1 FROM hour_periods other WHERE other.owner=p.owner AND other.id<>p.id AND other.start<? AND COALESCE(other.end,?)>p.start)`).bind(revision,b.end,b.reason.trim(),now,b.id,owner,b.oldEnd,owner,Math.max(p.end,b.end),b.end,now+1000),db.prepare('UPDATE hour_periods SET end=?,reviewed=0 WHERE id=? AND owner=? AND end=? AND EXISTS(SELECT 1 FROM hour_revisions WHERE id=?)').bind(b.end,b.id,owner,b.oldEnd,revision)]);return result[1].meta.changes?response({ok:true}):response({error:'O período mudou, cruza um mês fechado ou sobrepõe outra atividade. Atualize e confira.'},409)}
 if(b.action==='close'){if(typeof b.month!=='string'||!/^(20\d{2})-(0[1-9]|1[0-2])$/.test(b.month))return response({error:'Mês inválido.'},400);const [start,end]=monthBounds(b.month);if(now<hourBillingDates(b.month).close)return response({error:'O fechamento fica disponível a partir do dia 05 do mês seguinte, com pagamento previsto no dia 10. Os totais atuais são de conferência.'},400);const s=await hourState(db,owner);s.settings=personalHourSettings(s.settings,contacts);const snapshot=monthSnapshot(s,b.month);if(!snapshot.days.length)return response({error:'Não há horas encerradas neste mês.'},400);if(snapshot.days.some(d=>d.pending)||s.periods.some(p=>p.end===null&&p.start<end))return response({error:'Encerre atividades abertas e confira os períodos maiores que 16 horas.'},409);if(!s.settings.name)return response({error:'Preencha seu nome antes de fechar o mês.'},400);
 // The conditional insert validates the exact append-only data read above.
 // An attachment or review arriving during snapshot preparation forces a retry.
 const r=await db.prepare(`INSERT OR IGNORE INTO hour_archives(id,owner,month,start,end,at,data)
 SELECT ?,?,?,?,?,?,? WHERE NOT EXISTS(SELECT 1 FROM hour_periods WHERE owner=? AND end IS NULL AND start<?)
 AND (SELECT COUNT(*) FROM hour_periods WHERE owner=? AND start<? AND end>?)=?
 AND (SELECT COALESCE(SUM(reviewed),0) FROM hour_periods WHERE owner=? AND start<? AND end>?)=?
 AND (SELECT COUNT(*) FROM hour_evidence e JOIN hour_periods p ON e.period=p.id WHERE p.owner=? AND p.start<? AND p.end>?)=?
 AND (SELECT COUNT(*) FROM hour_revisions WHERE owner=?)=? AND COALESCE((SELECT cents FROM hour_goals WHERE owner=? AND month=?),0)=?`).bind(crypto.randomUUID(),owner,b.month,start,end,new Date(now).toISOString(),JSON.stringify(snapshot),owner,end,owner,end,start,snapshot.periods.length,owner,end,start,snapshot.periods.reduce((n,p)=>n+p.reviewed,0),owner,end,start,snapshot.evidence.length,owner,s.revisions.length,owner,b.month,snapshot.goal).run();return r.meta.changes?response({ok:true}):response({error:'O mês já está fechado ou os dados mudaram. Atualize e confira antes de fechar.'},409)}
 return response({error:'Ação inválida.'},400);
 }catch{return response({error:'Não foi possível salvar. Atualize para conferir o estado antes de tentar novamente.'},503)}}};}

export const MAX_EVIDENCE=20*1024*1024;
export async function readEvidence(req:Request){if(Number(req.headers.get('content-length'))>MAX_EVIDENCE)throw Error('size');if(!req.body)throw Error('empty');const chunks:Uint8Array[]=[];const reader=req.body.getReader();let size=0;while(true){const r=await reader.read();if(r.done)break;size+=r.value.byteLength;if(size>MAX_EVIDENCE){await reader.cancel();throw Error('size')}chunks.push(r.value)}if(!size)throw Error('empty');const bytes=new Uint8Array(size);let offset=0;for(const c of chunks){bytes.set(c,offset);offset+=c.length}return bytes}
export function evidenceType(name:string,bytes:Uint8Array){const ext=name.toLowerCase().split('.').pop();if(ext==='pdf'&&new TextDecoder().decode(bytes.slice(0,5))==='%PDF-')return 'application/pdf';if(ext==='png'&&[137,80,78,71,13,10,26,10].every((n,i)=>bytes[i]===n))return 'image/png';if(['jpg','jpeg'].includes(ext??'')&&bytes[0]===255&&bytes[1]===216&&bytes[2]===255)return 'image/jpeg';if(['docx','xlsx'].includes(ext??'')&&bytes[0]===80&&bytes[1]===75&&bytes[2]===3&&bytes[3]===4){const content=new TextDecoder().decode(bytes);if(content.includes('[Content_Types].xml')&&content.includes(ext==='docx'?'word/document.xml':'xl/workbook.xml')&&!content.includes('vbaProject.bin'))return ext==='docx'?'application/vnd.openxmlformats-officedocument.wordprocessingml.document':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}return null}
export function evidenceHandlers(db:DB,bucket:R2Bucket,getUser:()=>Promise<Identity|null>){return {
 GET:async(req:Request)=>{try{const u=await getUser();if(!u)return response({error:'Acesso não autorizado.'},401);const id=new URL(req.url).searchParams.get('id');if(!uuid(id))return response({error:'Comprovante não encontrado.'},404);const row=await db.prepare('SELECT key,name FROM hour_evidence WHERE id=? AND owner=?').bind(id,ownerOf(u)).first();if(!row)return response({error:'Comprovante não encontrado.'},404);const file=await bucket.get(row.key);if(!file)return response({error:'Arquivo indisponível. Tente novamente.'},503);return new Response(file.body,{headers:{'Content-Type':'application/octet-stream','Content-Disposition':`attachment; filename="comprovante"; filename*=UTF-8''${encodeURIComponent(row.name)}`,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'; sandbox",'Referrer-Policy':'no-referrer'}})}catch{return response({error:'Não foi possível baixar o comprovante.'},503)}},
 POST:async(req:Request)=>{let storedKey:string|null=null;try{const u=await getUser();if(!u)return response({error:'Acesso não autorizado.'},401);const origin=req.headers.get('origin');if(req.headers.get('x-prumo-request')!=='1'||req.headers.get('sec-fetch-site')==='cross-site'||origin&&origin!==new URL(req.url).origin||req.headers.get('content-type')!=='application/octet-stream')return response({error:'Solicitação não permitida.'},403);const owner=ownerOf(u),url=new URL(req.url),period=url.searchParams.get('period'),name=url.searchParams.get('name');if(!uuid(period)||!name||name.length>180||/[\x00-\x1f/\\]/.test(name))return response({error:'Nome do arquivo ou atividade inválidos.'},400);const p=await db.prepare('SELECT start,end FROM hour_periods WHERE id=? AND owner=?').bind(period,owner).first();if(!p)return response({error:'Atividade não encontrada.'},404);if(p.end===null)return response({error:'Encerre a atividade antes de anexar o comprovante.'},409);const existing=await db.prepare('SELECT COUNT(*) AS n FROM hour_evidence WHERE period=? AND owner=?').bind(period,owner).first();if(existing.n>=20)return response({error:'Limite de 20 arquivos por período atingido.'},400);let bytes:Uint8Array;try{bytes=await readEvidence(req)}catch{return response({error:'Envie um arquivo não vazio de até 20 MB.'},413)}const type=evidenceType(name,bytes);if(!type)return response({error:'Arquivo incompatível. Use PDF, DOCX ou XLSX sem macros, PNG ou JPEG.'},400);const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes as BufferSource))].map(n=>n.toString(16).padStart(2,'0')).join('');const prior=await db.prepare('SELECT id FROM hour_evidence WHERE owner=? AND period=? AND hash=?').bind(owner,period,hash).first();if(prior)return response({ok:true});const id=crypto.randomUUID(),key='hours/'+crypto.randomUUID()+'/'+id;await bucket.put(key,bytes as any,{httpMetadata:{contentType:type}});storedKey=key;const r=await db.prepare(`INSERT INTO hour_evidence(id,owner,period,key,name,size,hash,at) SELECT ?,?,?,?,?,?,?,? WHERE NOT EXISTS(SELECT 1 FROM hour_archives WHERE owner=? AND start<? AND end>?) AND (SELECT COUNT(*) FROM hour_evidence WHERE owner=? AND period=?)<20`).bind(id,owner,period,key,name,bytes.length,hash,new Date().toISOString(),owner,p.end,p.start,owner,period).run();if(!r.meta.changes){await bucket.delete(key);storedKey=null;return response({error:'Mês fechado ou limite de arquivos atingido. O comprovante não foi alterado.'},409)}storedKey=null;return response({ok:true})}catch{if(storedKey)await bucket.delete(storedKey).catch(()=>{});return response({error:'Não foi possível salvar o comprovante. Confira a lista antes de tentar novamente.'},503)}}};}
