import {boundedJSON,mutationAllowed,response,limited,resolveOwner} from './production-api';
import {emptyCatalog,menuCatalogSchema,type MenuCatalog} from './menu-catalog';
import {normalizeCatalog} from './catalog-normalize';
import {logError} from './log';
import type {Identity} from './production-api';
type DB={prepare:(sql:string)=>any};
const normalized=(value:string)=>value.trim().replace(/\s+/g,' ');
export const CATALOG_LIMIT_BYTES=1_800_000;

export function menuCatalogHandlers(db:DB,getUser:()=>Promise<Identity|null>){return {
 GET:async()=>{try{const user=await getUser();if(!user)return response({error:'Entre com sua conta para acessar.'},401);const owner=await resolveOwner(db,user);if(await limited(db,owner))return response({error:'Muitas solicitações. Aguarde um minuto.'},429);const row=await db.prepare('SELECT data,version FROM menu_catalogs WHERE owner=?').bind(owner).first();if(!row)return response({...emptyCatalog(),catalogBytes:0,catalogLimit:CATALOG_LIMIT_BYTES});const {catalog,invalid}=normalizeCatalog(JSON.parse(row.data),row.version);if(invalid.length)logError('catalog','catalog_invalid_items',new Error(JSON.stringify(invalid.reduce((a,x)=>(a[x.section]=(a[x.section]??0)+1,a),{} as Record<string,number>))));return response({...catalog,needsReview:invalid,catalogBytes:new TextEncoder().encode(row.data).length,catalogLimit:CATALOG_LIMIT_BYTES})}catch(err){logError('catalog','db_error',err);return response({error:'Não foi possível carregar os cardápios.',code:'db_error'},503)}},
 POST:async(req:Request)=>{try{const user=await getUser();if(!user)return response({error:'Entre com sua conta para salvar.'},401);if(!mutationAllowed(req))return response({error:'Solicitação não permitida. Atualize a página e tente novamente.'},403);const owner=await resolveOwner(db,user);if(await limited(db,owner))return response({error:'Muitas solicitações. Aguarde um minuto.'},429);let body:any;try{body=await boundedJSON(req)}catch(err){const tooLarge=err instanceof Error&&err.message==='too_large';return response({error:tooLarge?'Catálogo no limite. Arquive fichas antigas antes de adicionar novas.':'Dados inválidos.',code:tooLarge?'catalog_too_large':'invalid'},tooLarge?413:400)}const parsed=menuCatalogSchema.safeParse(body?.data);if(!parsed.success)return response({error:'Confira os dados do cardápio.',code:'invalid'},400);const old=await db.prepare('SELECT data,version FROM menu_catalogs WHERE owner=?').bind(owner).first();if((old?.version??0)!==parsed.data.version)return response({error:'Os cardápios foram alterados em outro acesso. Recarregue e tente novamente.',code:'conflict'},409);const prior=old?normalizeCatalog(JSON.parse(old.data),old.version):null;const data:MenuCatalog={...parsed.data,preparations:[...new Set(parsed.data.preparations.map(normalized))],menus:parsed.data.menus.map(m=>({...m,name:normalized(m.name),items:[...new Set(m.items.map(normalized))]}))};const now=new Date().toISOString(),nextVersion=data.version+1,serialized=JSON.stringify({...data,version:nextVersion,quarantine:prior?.quarantine??[]}),catalogBytes=new TextEncoder().encode(serialized).length;if(catalogBytes>CATALOG_LIMIT_BYTES)return response({error:'Catálogo no limite. Arquive fichas antigas antes de adicionar novas.',code:'catalog_too_large'},413);const result=old?await db.prepare('UPDATE menu_catalogs SET data=?,version=?,updated=? WHERE owner=? AND version=?').bind(serialized,nextVersion,now,owner,data.version).run():await db.prepare('INSERT OR IGNORE INTO menu_catalogs(owner,data,version,updated) VALUES(?,?,?,?)').bind(owner,serialized,nextVersion,now).run();if(!result.meta.changes)return response({error:'Conflito de gravação. Recarregue os cardápios.',code:'conflict'},409);return response({...data,version:nextVersion,catalogBytes,catalogLimit:CATALOG_LIMIT_BYTES,needsReview:prior?.invalid??[]})}catch(err){logError('catalog','db_error',err);return response({error:'Não foi possível salvar os cardápios.',code:'db_error'},503)}}
};}
