import {z} from 'zod';
import {unitCost,type Unit} from './units';

export const proteinChoices=['Filé de peito de frango','Linguiça tipo toscana','Bisteca suína','Bife bovino','Peito de frango com osso','Rabada'];
export const defaultPreparations=['Arroz','Feijão','Macarrão',...proteinChoices];
export type MenuAudience='campo'|'adm'|'dietas';
export type MenuTemplate={id:string;name:string;audience:MenuAudience;items:string[]};
export type TechnicalIngredient={name:string;qty:number;unit:string;unitPrice:number;priceUnit?:string};
export type TechnicalCost={name:string;value:number};
export type CatalogRecord={version?:number;revision?:number;archived?:boolean;updatedAt?:string|null;updatedBy?:string};
export type Equipment=CatalogRecord&{id:string;name:string;category:string;number:string;size:string;weightKg:number|null;capacity:string;notes:string};
export type NutritionFacts={energyKcal:number|null;carbohydrates:number|null;protein:number|null;totalFat:number|null;saturatedFat:number|null;fiber:number|null;sodium:number|null;calcium:number|null;iron:number|null};
export type TechnicalSheet=CatalogRecord&{id:string;preparation:string;code:string;category:string;responsible:string;prepMinutes:number|null;cookMinutes:number|null;yieldKg:number|null;portions:number|null;portionGrams:number|null;equipmentIds:string[];nutrition:NutritionFacts;photoVersion:string|null;ingredients:TechnicalIngredient[];additionalCosts:TechnicalCost[];instructions:string};
export type CatalogReview={section:'preparations'|'menus'|'technicalSheets'|'equipment';index:number;id?:string;issues:string[]};
export type MenuCatalog={version:number;preparations:string[];menus:MenuTemplate[];technicalSheets:TechnicalSheet[];equipment:Equipment[];needsReview?:CatalogReview[];catalogBytes?:number;catalogLimit?:number};
const label=z.string().trim().min(1).max(160);
const optionalPositive=z.number().positive().nullable();
export const nutritionSchema=z.object({energyKcal:z.number().nonnegative().nullable(),carbohydrates:z.number().nonnegative().nullable(),protein:z.number().nonnegative().nullable(),totalFat:z.number().nonnegative().nullable(),saturatedFat:z.number().nonnegative().nullable(),fiber:z.number().nonnegative().nullable(),sodium:z.number().nonnegative().nullable(),calcium:z.number().nonnegative().nullable(),iron:z.number().nonnegative().nullable()});
export const menuTemplateSchema=z.object({id:z.string().uuid(),name:label,audience:z.enum(['campo','adm','dietas']),items:z.array(label).min(1).max(40)});
const catalogRecordSchema={version:z.number().int().positive().optional(),revision:z.number().int().positive().optional(),archived:z.boolean().optional(),updatedAt:z.string().datetime().nullable().optional(),updatedBy:z.string().max(200).optional()};
export const technicalSheetSchema=z.object({id:z.string().uuid(),preparation:label,code:z.string().max(50).default(''),category:z.string().max(100).default(''),responsible:z.string().max(120).default(''),prepMinutes:z.number().nonnegative().nullable().default(null),cookMinutes:z.number().nonnegative().nullable().default(null),yieldKg:optionalPositive,portions:z.number().int().positive().nullable(),portionGrams:optionalPositive,equipmentIds:z.array(z.string().uuid()).max(100).default([]),nutrition:nutritionSchema.default({energyKcal:null,carbohydrates:null,protein:null,totalFat:null,saturatedFat:null,fiber:null,sodium:null,calcium:null,iron:null}),photoVersion:z.string().max(40).nullable().default(null),ingredients:z.array(z.object({name:z.string().trim().min(1).max(100),qty:z.number().positive(),unit:z.string().trim().min(1).max(20),unitPrice:z.number().nonnegative(),priceUnit:z.string().trim().min(1).max(20).optional()})).max(100),additionalCosts:z.array(z.object({name:z.string().trim().min(1).max(100),value:z.number().nonnegative()})).max(50),instructions:z.string().trim().max(3000),...catalogRecordSchema});
export const equipmentSchema=z.object({id:z.string().uuid(),name:label,category:z.string().trim().min(1).max(80),number:z.string().max(50),size:z.string().max(80),weightKg:z.number().nonnegative().nullable(),capacity:z.string().max(80),notes:z.string().max(300),...catalogRecordSchema});
export const menuCatalogSchema=z.object({version:z.number().int().nonnegative(),preparations:z.array(label).max(300),menus:z.array(menuTemplateSchema).max(300),technicalSheets:z.array(technicalSheetSchema).max(300).default([]),equipment:z.array(equipmentSchema).max(500).default([])});
export const emptyNutrition=():NutritionFacts=>({energyKcal:null,carbohydrates:null,protein:null,totalFat:null,saturatedFat:null,fiber:null,sodium:null,calcium:null,iron:null});
export const emptyCatalog=():MenuCatalog=>({version:0,preparations:[...defaultPreparations],menus:[],technicalSheets:[],equipment:[]});
export const audienceLabel=(value:MenuAudience)=>value==='campo'?'Campo':value==='adm'?'Administrativo':'Dietas especiais/restritivas';
const canonical=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('pt-BR').replace(/\b(tipo|assado|assada|suino|suina)\b/g,'').replace(/\s+/g,' ').trim();
export const preparationMatches=(registered:string,item:string)=>canonical(registered)===canonical(item);
export const technicalSheetCost=(sheet:TechnicalSheet)=>sheet.ingredients.reduce((sum,item)=>sum+(item.priceUnit?unitCost(item.qty,item.unit as Unit,item.unitPrice,item.priceUnit as Unit):item.qty*item.unitPrice),0)+sheet.additionalCosts.reduce((sum,item)=>sum+item.value,0);
