import {boundedJSON,mutationAllowed,response,limited,resolveOwner} from './production-api';
import {emptyCatalog,menuCatalogSchema,type MenuCatalog} from './menu-catalog';
import type {Identity} from './production-api';
type DB={prepare:(sql:string)=>any};
const normalized=(value:string)=>value.trim().replace(/\s+/g,' ');

export function menuCatalogHandlers(db:DB,getUser:()=>Promise<Identity|null>){return {
 GET:async()=>{try{const user=await getUser();if(!user)return response({error:'Entre com sua conta para acessar.'},401);const owner=await resolveOwner(db,user);if(await limited(db,owner))return response({error:'Muitas solicitações. Aguarde um minuto.'},429);const row=await db.prepare('SELECT data,version FROM menu_catalogs WHERE owner=?').bind(owner).first();if(!row)return response(emptyCatalog());const saved=JSON.parse(row.data);return response({...saved,technicalSheets:Array.isArray(saved.technicalSheets)?saved.technicalSheets:[],version:row.version})}catch{return response({error:'Não foi possível carregar os cardápios.'},503)}},
 POST:async(req:Request)=>{try{const user=await getUser();if(!user)return response({error:'Entre com sua conta para salvar.'},401);if(!mutationAllowed(req))return response({error:'Solicitação não permitida. Atualize a página e tente novamente.'},403);const owner=await resolveOwner(db,user);if(await limited(db,owner))return response({error:'Muitas solicitações. Aguarde um minuto.'},429);let body:any;try{body=await boundedJSON(req)}catch{return response({error:'Dados inválidos.'},400)}const parsed=menuCatalogSchema.safeParse(body?.data);if(!parsed.success)return response({error:'Confira os dados do cardápio.'},400);const old=await db.prepare('SELECT version FROM menu_catalogs WHERE owner=?').bind(owner).first();if((old?.version??0)!==parsed.data.version)return response({error:'Os cardápios foram alterados em outro acesso. Recarregue e tente novamente.'},409);const data:MenuCatalog={...parsed.data,preparations:[...new Set(parsed.data.preparations.map(normalized))],menus:parsed.data.menus.map(m=>({...m,name:normalized(m.name),items:[...new Set(m.items.map(normalized))]}))};const now=new Date().toISOString(),nextVersion=data.version+1,serialized=JSON.stringify({...data,version:nextVersion});if(serialized.length>250000)return response({error:'Catálogo muito extenso.'},413);const result=old?await db.prepare('UPDATE menu_catalogs SET data=?,version=?,updated=? WHERE owner=? AND version=?').bind(serialized,nextVersion,now,owner,data.version).run():await db.prepare('INSERT OR IGNORE INTO menu_catalogs(owner,data,version,updated) VALUES(?,?,?,?)').bind(owner,serialized,nextVersion,now).run();if(!result.meta.changes)return response({error:'Conflito de gravação. Recarregue os cardápios.'},409);return response({...data,version:nextVersion})}catch{return response({error:'Não foi possível salvar os cardápios.'},503)}}
};}
