import {normal,bold} from './pdf-font';
import {GSI_BLACK,GSI_RED,GSI_STATIONERY,GSI_YELLOW} from './gsi-brand';
import {jsPDF} from 'jspdf';
import autoTable from 'jspdf-autotable';
import {Production,fmt,money,time,net,totals,prepStats,prepSourceWeights,productionSourceTotals,routeDispatch,entryTime,dietLabel,destinationItems,mealComposition,totalUnallocatedWeight,specialDietItems,specialDietNetWeight,isSpecialLunchbox} from './uan';

function groupedDestinations(s:Production){return routeDispatch(s).map(g=>[
 g.route+'\n'+g.work.name+'\nTotal: '+fmt(g.kg,3)+' kg',
 destinationItems(s,g).map(item=>item.text+' - '+fmt(item.kg,3)+' kg').join('\n'),
 g.transport.join('\n')+'\n\nColeta: '+[...new Set(g.entries.map(e=>e.operator))].join(', ')+'\nPrimeiro: '+entryTime(g.entries[0])+'\nÚltimo: '+entryTime(g.entries[g.entries.length-1])
]);}

export function makeReport(s:Production,detailed=false){
 const doc=new jsPDF();doc.addFileToVFS('Prumo.ttf',normal);doc.addFont('Prumo.ttf','Prumo','normal');doc.addFileToVFS('PrumoBold.ttf',bold);doc.addFont('PrumoBold.ttf','Prumo','bold');doc.setFont('Prumo','normal');
 const t=totals(s),sourceTotals=productionSourceTotals(s),specialEntries=s.entries.filter(e=>!e.cancelled&&e.lunchboxes?.some(isSpecialLunchbox)),specialKg=specialEntries.reduce((sum,e)=>sum+specialDietNetWeight(e),0),specialCount=specialEntries.reduce((sum,e)=>sum+(e.lunchboxes?.filter(isSpecialLunchbox).length??0),0),plannedKnown=s.works.reduce((a,w)=>a+(w.worker??0)+(w.admin??0),0),plannedComplete=s.works.length>0&&s.works.every(w=>w.worker!==null&&w.admin!==null),servedKnown=s.works.reduce((a,w)=>a+(w.servedWorker??0)+(w.servedAdmin??0),0),servedComplete=s.works.length>0&&s.works.every(w=>w.servedWorker!==null&&w.servedAdmin!==null),revenueKnown=s.works.reduce((a,w)=>a+(w.worker??0)*s.settings.workerPrice+(w.admin??0)*s.settings.adminPrice,0),actualRevenueKnown=s.works.reduce((a,w)=>a+(w.servedWorker??0)*s.settings.workerPrice+(w.servedAdmin??0)*s.settings.adminPrice,0);let y=52;const width=182;
 const newPage=()=>{doc.addPage();y=52};
 const text=(value:string,size=10,color='#1c1c1c')=>{doc.setFontSize(size);doc.setTextColor(color);const lines=doc.splitTextToSize(value,width);if(y+lines.length*size*.4+(size>=11?12:0)>252)newPage();doc.text(lines,14,y);y+=lines.length*size*.42+4};
 const table=(head:string[],body:any[][])=>{if(y>220)newPage();autoTable(doc,{startY:y,head:[head],body,rowPageBreak:'avoid',margin:{left:14,right:14,top:52,bottom:42},styles:{font:'Prumo',fontSize:8,cellPadding:2.7,overflow:'linebreak',fontStyle:'normal',textColor:GSI_BLACK},headStyles:{fillColor:GSI_RED,textColor:[255,255,255]},alternateRowStyles:{fillColor:[255,249,219]}});y=(doc as any).lastAutoTable.finalY+9};
 text('RELATÓRIO DE PRODUÇÃO',17,'#e20023');text('PRUMO SYSTEM | '+s.date.split('-').reverse().join('/')+' | Aracaju-SE | Emitido em '+time(new Date().toISOString()),9);text('Responsável declarado: '+s.operator+' | Produção '+s.id.slice(0,8),9);
 table(['Peso líquido total','Dietas especiais (separado)','Ingredientes','CMV / custo servida'],[[fmt(t.weight)+' kg',specialCount+' un. / '+fmt(specialKg,3)+' kg',money(t.cost)+(t.complete?'':' (parcial)'),t.cmv===null?'A apurar':fmt(t.cmv)+'% / '+money(t.costMeal)]]);
 text('1. Resultado gerencial',12,'#e20023');table(['Indicador','Valor','Critério'],[['Refeições previstas / servidas',fmt(plannedKnown,0)+(plannedComplete?'':' (parcial)')+' / '+fmt(servedKnown,0)+(servedComplete?'':' (parcial)'),'Soma dos valores preenchidos por obra'],['Receita prevista / sobre servidas',money(revenueKnown)+(plannedComplete?'':' (parcial)')+' / '+money(actualRevenueKnown)+(servedComplete?'':' (parcial)'),'Operacional '+money(s.settings.workerPrice)+'; ADM '+money(s.settings.adminPrice)],['CMV projetado',t.projected===null?'A apurar':fmt(t.projected)+'%','Ingredientes do lote / receita prevista completa'],['Tributo efetivo / embalagem',(s.settings.tax===null?'A apurar':fmt(s.settings.tax)+'%')+' / '+money(s.settings.packaging),'Alíquota declarada; embalagem por refeição'],['Outras despesas / resultado',money(s.settings.other)+' / '+money(t.margin),'Resultado após custos declarados completos; não é lucro contábil'],['Referência presumida / diferença','R$ 5,30 / '+money(t.costMeal===null?null:5.3-t.costMeal),'Diferença não comprova economia sem igualar escopo e cardápio']]);
 text('2. Rendimento por preparo e origem',12,'#e20023');table(['Preparo','Cru kg','GNs / recip. kg','Marmitas normais kg','Marmitas especiais kg','Sobra limpa kg','Cozido total kg','Rendimento'],[...s.preps.map(p=>{const r=prepSourceWeights(s,p),partial=r.ready===null?' (parcial)':'';return[p.name+(p.closed?'':' (aberto)'),fmt(p.raw),fmt(r.containers),fmt(r.normal),fmt(r.special),fmt(r.remaining),fmt(r.cooked)+partial,p.raw>0?fmt(r.cooked/p.raw*100)+'%'+partial:'A apurar']}),['TOTAL GERAL',fmt(sourceTotals.raw),fmt(sourceTotals.containers),fmt(sourceTotals.normal),fmt(sourceTotals.special),fmt(sourceTotals.remaining),fmt(sourceTotals.cooked)+(sourceTotals.complete?'':' (parcial)'),sourceTotals.yield===null?'A apurar':fmt(sourceTotals.yield*100)+'%'+(sourceTotals.complete?'':' (parcial)')]]);
 text('Cozido total = GNs/recipientes + marmitas normais + marmitas especiais + sobra limpa aproveitável. Rendimento = cozido total / peso cru. Dietas especiais permanecem em coluna própria e entram uma única vez no total.',8,'#555555');
 if(y>220)newPage();table(['Preparo','Custo do lote','R$/kg cozido','Porção / custo'],s.preps.map(p=>{const a=prepStats(s,p);return[p.name,money(p.cost)+(p.costComplete?'':' *'),money(a.costKg),p.portion?fmt(p.portion,0)+'g: '+money(a.costKg===null?null:a.costKg*p.portion/1000):'não definida']}));
 if(s.preps.length){if(y+60>252)newPage();text('Peso cozido total por preparo (kg)',10,'#e20023');const max=Math.max(1,...s.preps.map(p=>prepSourceWeights(s,p).cooked));for(const p of s.preps){if(y>244)newPage();const r=prepSourceWeights(s,p),kg=r.cooked;doc.setFontSize(8);doc.setTextColor(...GSI_BLACK);doc.text(p.name.length>32?p.name.slice(0,31)+'...':p.name,14,y+3);doc.setFillColor(255,241,164);doc.rect(82,y,93,4,'F');doc.setFillColor(...GSI_YELLOW);doc.rect(82,y,93*kg/max,4,'F');doc.text(fmt(kg)+(r.ready===null?' (parcial)':''),180,y+3,{align:'right'});y+=9}y+=5}
 text('3. Dietas especiais e restritivas - valores separados',12,'#e20023');const dietRows=specialDietItems(s);if(dietRows.length){table(['Destino / dieta','Item','Quantidade / medida','Peso informado'],dietRows.map(r=>[r.destination+'\n'+r.diet,r.item,r.quantity+' marmita(s)'+(r.units?' / '+r.units+' un.':'')+(r.measures.length?' / '+r.measures.join(', '):''),r.grams?fmt(r.grams/1000,3)+' kg':'A apurar']));text('Total de dietas especiais/restritivas: '+specialCount+' marmita(s). Peso líquido proporcional dos grupos: '+fmt(specialKg,3)+' kg. No rendimento por preparo, esses pesos aparecem somente na coluna Marmitas especiais e não são confundidos com GNs ou marmitas normais.',8,'#555555')}else text('Nenhuma dieta especial ou restritiva registrada nesta produção.',9,'#555555');
 text('4. Temperaturas e cobertura da coleta',12,'#e20023');table(['Preparo','Medições','Média / mín. / máx. °C','Blocos medidos','Até 60 °C'],s.preps.map(p=>{const a=prepStats(s,p);return[p.name,a.temps.length,fmt(a.mean,1)+' / '+fmt(a.min,1)+' / '+fmt(a.max,1),a.covered+' de '+a.blocks,a.below]}));text('Método declarado: termômetro de espeto no centro geométrico. A média é amostral e não comprova segurança de todo o lote. Avaliar desvios com o RT.',8,'#555555');
 const alerts=s.entries.filter(e=>!e.cancelled&&e.temperature!==null&&e.temperature<=60);if(alerts.length){text('Medições em alerta - avaliação individual',11,'#e20023');table(['Quando / quem','Preparo / obra','°C','Ação registrada'],alerts.map(e=>[entryTime(e)+' / '+e.operator,(e.lunchboxes?'Marmitas':s.preps.find(p=>p.id===e.prep)?.name)+' / '+(s.works.find(w=>w.id===e.work)?.name||'Destino a informar'),fmt(e.temperature,1),e.note||'Pendente']))}
 text('5. Envios agrupados por rota e obra',12,'#e20023');table(['Rota / obra','Recipientes por alimento e grupo Marmitas','Transporte e registro'],groupedDestinations(s));text('Obras com o mesmo nome são consolidadas em um único destino. As marmitas permanecem no grupo Marmitas, com subtotais entre normais e especiais, e cada unidade é contada uma única vez.',8,'#555555');
 if(s.entries.some(e=>!e.cancelled&&e.lunchboxes)){text('Composição das marmitas por destino',12,'#e20023');table(['Rota / obra / registro','Quantidade','Componentes por marmita'],routeDispatch(s).flatMap(g=>g.entries.filter(e=>e.lunchboxes).flatMap(e=>mealComposition(s,e).map(c=>[g.route+' / '+g.work.name+' / '+e.id.slice(0,8),c.count,c.text]))));text('Unidades e medidas caseiras não são convertidas em gramas. Peso de marmitas ainda sem alocação por preparo: '+fmt(totalUnallocatedWeight(s),3)+' kg.',8,'#555555')}
 text('6. Como, quando e por quem',12,'#e20023');table(['Preparo','Primeira / última pesagem','Responsáveis','Fechamento / observações'],s.preps.map(p=>{const a=prepStats(s,p);return[p.name,a.entries.length?entryTime(a.entries[0])+' / '+entryTime(a.entries[a.entries.length-1]):'Sem coleta',[...new Set(a.entries.map(e=>e.operator))].join(', ')||'A informar','Ficou na unidade: '+fmt(p.remaining)+' kg; perdas/amostras: '+fmt(p.loss)+' kg; FC: '+(p.clean?fmt(p.raw/p.clean):'a apurar')+'. '+p.note]}));
 if(detailed){text('7. Rastreabilidade de cada pesagem',12,'#e20023');table(['Data/hora / pessoa','Preparo / obra','Recipiente / kg','°C / transporte','Observação'],s.entries.map(e=>[entryTime(e)+'\n'+e.operator,(e.lunchboxes?'Marmitas completas':s.preps.find(p=>p.id===e.prep)?.name)+'\n'+(s.works.find(w=>w.id===e.work)?.name||'Destino a informar'),e.type+' x '+e.quantity+'\nBruto '+fmt(e.gross)+'; tara '+fmt(e.tare,3)+'; líq. '+fmt(net(e)),fmt(e.temperature,1)+'\n'+e.vehicle+' / '+e.driver+' / '+(e.route||'Rota não informada'),(e.cancelled?'CANCELADO. ':'')+[dietLabel(e),e.dietNote,e.note].filter(Boolean).join(' / ')]));if(s.audit.length){text('Histórico de alterações',12,'#e20023');table(['Quando','Quem','O que foi feito'],s.audit.map(a=>[time(a.at),a.operator,a.action+(a.changes?.length?' | '+a.changes.map(c=>c.id.slice(0,8)+': '+c.fields.join(', ')).join('; '):'')]))}}
 text('Pendências: '+([s.entries.some(e=>!e.cancelled&&(!e.work||!e.driver||!e.vehicle))?'recipientes com destino/transporte a informar':null,totalUnallocatedWeight(s)>=0.005?'pesos de marmitas sem alocação por preparo':null,!t.complete?'custos de ingredientes incompletos':null,t.actualRevenue===null?'refeições servidas não encerradas':null,s.settings.tax===null?'alíquota não informada':null,!s.settings.complete?'despesas/rateios não confirmados':null,s.preps.some(p=>!p.closed)?'lotes em aberto':null].filter(Boolean).join('; ')||'nenhuma entre os campos verificados')+'.',9);
 const pages=doc.getNumberOfPages();for(let i=1;i<=pages;i++){doc.setPage(i);doc.addImage(GSI_STATIONERY,'PNG',0,0,210,297,undefined,'FAST');doc.setFontSize(8);doc.setTextColor(...GSI_RED);doc.text('PRUMO SYSTEM | Uso interno | '+s.date,14,286);doc.setTextColor(...GSI_BLACK);doc.text(i+' / '+pages,188,286)}return doc;
}
