export const names=['Arroz','Feijão','Macarrão','Bisteca bovina assada','Filé de peito de frango assado','Peito de frango com osso assado','Linguiça toscana suína assada','Rabada','Carne moída cozida','Bisteca suína assada'];
export const types=['Cuba','Cuba branca extra P','GN PP','GN P','GN M','GN G','Cooler','Sobra limpa'];
export type Prep={id:string;name:string;raw:number;clean:number|null;portion:number|null;cost:number|null;ingredients?:{name:string;qty:string;unit:string;price:string}[];costComplete:boolean;remaining:number|null;loss:number|null;closed:boolean;note:string};
export type Work={id:string;name:string;worker:number|null;admin:number|null;servedWorker:number|null;servedAdmin:number|null;vehicle:string;route?:string;driver:string};
export type MealComponent={name:string;prep:string;item?:string;grams:number|null;units:number|null;utensil:string};
export type Lunchbox={components:MealComponent[];diet?:string;dietNote?:string};
export type Entry={lunchboxes?:Lunchbox[];diet?:string;dietNote?:string;deviceOffset?:number;equipmentId?:string;id:string;prep:string;work:string;type:string;quantity:number;tare:number;gross:number;temperature:number|null;vehicle:string;route?:string;driver:string;operator:string;at:string;created:string;note:string;cancelled:boolean};
export type Production={id:string;date:string;version:number;operator:string;preps:Prep[];works:Work[];entries:Entry[];taras:Record<string,number|null>;menuSelection?:Partial<Record<'campo'|'adm'|'dietas',string>>;weighingFinalizedAt?:Record<string,string>;settings:{workerPrice:number;adminPrice:number;tax:number|null;other:number|null;packaging:number|null;complete:boolean};audit:{at:string;operator:string;action:string;account?:string;changes?:{id:string;fields:string[]}[]}[]};
export const num=(v:unknown):number|null=>{if(v===null||v===undefined||String(v).trim()==='')return null;const n=Number(String(v).replace(',','.'));return Number.isFinite(n)?n:null};
export const fmt=(v:number|null|undefined,d=2)=>v==null?'A apurar':v.toLocaleString('pt-BR',{minimumFractionDigits:d,maximumFractionDigits:d});
export const money=(v:number|null|undefined)=>v==null?'A apurar':v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export const time=(v:string)=>new Date(v).toLocaleString('pt-BR',{timeZone:'America/Bahia',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'});
export const net=(e:Entry)=>e.gross-e.tare*e.quantity;
export const isSpecialLunchbox=(box:Lunchbox)=>box.diet==='especial'||box.diet==='restritiva';
export type EntryKind='container'|'lunchbox'|'legacyLunchbox';
export const entryKind=(e:Entry):EntryKind=>e.lunchboxes?.length?'lunchbox':isLunchbox(e.type)?'legacyLunchbox':'container';
export const isKnownSpecial=(diet?:string)=>diet==='especial'||diet==='restritiva';
export const isUnclassifiedDiet=(diet?:string)=>diet!=='normal'&&!isKnownSpecial(diet);
const componentWeight=(box:Lunchbox,id:string)=>box.components.filter(c=>c.prep===id).reduce((sum,c)=>sum+(c.grams??0)/1000,0);
export const normalLunchboxPrepWeight=(e:Entry,id:string)=>e.lunchboxes?e.lunchboxes.filter(b=>!isSpecialLunchbox(b)).reduce((a,b)=>a+componentWeight(b,id),0):0;
export const specialDietPrepWeight=(e:Entry,id:string)=>e.lunchboxes?e.lunchboxes.filter(isSpecialLunchbox).reduce((a,b)=>a+componentWeight(b,id),0):0;
export const prepWeight=(e:Entry,id:string)=>e.lunchboxes?normalLunchboxPrepWeight(e,id)+specialDietPrepWeight(e,id):e.prep===id?net(e):0;
export const unallocatedWeight=(s:Production)=>s.entries.filter(e=>!e.cancelled&&e.lunchboxes).reduce((a,e)=>{const boxes=e.lunchboxes??[],normal=boxes.filter(b=>!isSpecialLunchbox(b));if(!normal.length)return a;const estimated=net(e)/Math.max(1,boxes.length);return a+normal.reduce((sum,b)=>sum+Math.max(0,estimated-b.components.reduce((v,c)=>v+(c.grams??0)/1000,0)),0)},0);
export const specialDietUnallocatedWeight=(s:Production)=>s.entries.filter(e=>!e.cancelled&&e.lunchboxes).reduce((a,e)=>{const boxes=e.lunchboxes??[],special=boxes.filter(isSpecialLunchbox);if(!special.length)return a;const estimated=net(e)/Math.max(1,boxes.length);return a+special.reduce((sum,b)=>sum+Math.max(0,estimated-b.components.reduce((v,c)=>v+(c.grams??0)/1000,0)),0)},0);
export const totalUnallocatedWeight=(s:Production)=>unallocatedWeight(s)+specialDietUnallocatedWeight(s);
export function prepSourceWeights(s:Production,p:Prep){let containers=0,normal=0,unclassified=0,special=0,legacyNormal=0,legacySpecial=0,specialPending=false;for(const e of s.entries.filter(e=>!e.cancelled)){const kind=entryKind(e);if(kind==='container'&&e.prep===p.id){containers+=net(e);continue}if(kind==='legacyLunchbox'&&e.prep===p.id){if(isKnownSpecial(e.diet))legacySpecial+=net(e);else legacyNormal+=net(e);continue}if(kind==='lunchbox')for(const box of e.lunchboxes??[])for(const c of box.components.filter(c=>c.prep===p.id)){if(isKnownSpecial(box.diet)){special+=(c.grams??0)/1000;if(c.grams===null)specialPending=true}else if(box.diet==='normal')normal+=(c.grams??0)/1000;else unclassified+=(c.grams??0)/1000;}}const remaining=p.closed?(p.remaining??0):0,cookedNormal=containers+normal+legacyNormal+remaining,cookedTotal=cookedNormal+unclassified+special+legacySpecial,normalPending=unallocatedWeight(s)>=0.005,anyPending=totalUnallocatedWeight(s)>=0.005||specialPending,readyNormal=p.closed&&!normalPending?cookedNormal:null,readyTotal=p.closed&&!anyPending?cookedTotal:null,yieldNormal=readyNormal===null?null:readyNormal/p.raw,yieldTotal=readyTotal===null?null:readyTotal/p.raw;return{containers,normal,unclassified,special,legacyNormal,legacySpecial,remaining,cookedNormal,cookedTotal,readyNormal,readyTotal,specialPending,yieldTotal,cooked:cookedNormal,ready:readyNormal,yield:yieldNormal}}
export function productionSourceTotals(s:Production){const rows=s.preps.map(p=>({p,...prepSourceWeights(s,p)})),raw=rows.reduce((a,r)=>a+r.p.raw,0),containers=rows.reduce((a,r)=>a+r.containers,0),normal=rows.reduce((a,r)=>a+r.normal+r.legacyNormal,0),unclassified=rows.reduce((a,r)=>a+r.unclassified,0),special=rows.reduce((a,r)=>a+r.special+r.legacySpecial,0),remaining=rows.reduce((a,r)=>a+r.remaining,0),cookedNormal=rows.reduce((a,r)=>a+r.cookedNormal,0),cookedTotal=rows.reduce((a,r)=>a+r.cookedTotal,0),complete=rows.length>0&&rows.every(r=>r.readyNormal!==null);return{raw,containers,normal,unclassified,special,remaining,cookedNormal,cookedTotal,cooked:cookedNormal,complete,yield:raw>0?cookedNormal/raw:null,yieldTotal:raw>0?cookedTotal/raw:null}}
export function prepStats(s:Production,p:Prep){const es=s.entries.filter(e=>!e.cancelled&&(e.prep===p.id||e.lunchboxes?.some(b=>b.components.some(c=>c.prep===p.id))));const source=prepSourceWeights(s,p),weight=source.cookedTotal-source.remaining;const ts=es.flatMap(e=>e.lunchboxes||e.temperature==null?[]:[e.temperature]);let covered=0;for(let i=0;i<es.length;i+=20)if(es.slice(i,i+20).some(e=>!e.lunchboxes&&e.temperature!==null))covered++;const ready=source.readyNormal;return{entries:es,weight,ready,yield:source.yield,costKg:ready&&p.costComplete&&p.cost!==null?p.cost/ready:null,temps:ts,mean:ts.length?ts.reduce((a,b)=>a+b,0)/ts.length:null,min:ts.length?Math.min(...ts):null,max:ts.length?Math.max(...ts):null,below:ts.filter(t=>t<=60).length,covered,blocks:Math.ceil(es.length/20),due:es.length===0||es.length%20===0||!es.slice(Math.floor(es.length/20)*20).some(e=>e.temperature!==null)}}
export function totals(s:Production){const ps=s.preps.map(p=>prepStats(s,p));const cost=s.preps.reduce((a,p)=>a+(p.cost??0),0);const complete=s.preps.length>0&&s.preps.every(p=>p.costComplete&&p.cost!==null);const plannedComplete=s.works.length>0&&s.works.every(w=>w.worker!==null&&w.admin!==null);const planned=plannedComplete?s.works.reduce((a,w)=>a+(w.worker??0)+(w.admin??0),0):null;const revenue=plannedComplete?s.works.reduce((a,w)=>a+(w.worker??0)*s.settings.workerPrice+(w.admin??0)*s.settings.adminPrice,0):null;const actualComplete=s.works.length>0&&s.works.every(w=>w.servedWorker!==null&&w.servedAdmin!==null);const served=s.works.reduce((a,w)=>a+(w.servedWorker??0)+(w.servedAdmin??0),0);const actualRevenue=actualComplete?s.works.reduce((a,w)=>a+(w.servedWorker??0)*s.settings.workerPrice+(w.servedAdmin??0)*s.settings.adminPrice,0):null;const margin=complete&&actualRevenue!==null&&s.settings.complete&&s.settings.tax!==null&&s.settings.other!==null&&s.settings.packaging!==null?actualRevenue*(1-s.settings.tax/100)-cost-s.settings.other-served*s.settings.packaging:null;return{weight:s.entries.filter(e=>!e.cancelled).reduce((a,e)=>a+net(e),0),cost,complete,planned,revenue,actualRevenue,served,cmv:complete&&actualRevenue?cost/actualRevenue*100:null,projected:complete&&revenue?cost/revenue*100:null,costMeal:complete&&served&&actualComplete?cost/served:null,margin};}
export function fresh(date:string,operator:string):Production{return{id:crypto.randomUUID(),date,operator,version:0,preps:[],works:[],entries:[],taras:Object.fromEntries(types.map(t=>[t,null])),settings:{workerPrice:10.9,adminPrice:13.5,tax:null,other:null,packaging:null,complete:false},audit:[]}}

export function dispatchSummary(s:Production){return s.works.map(w=>{const entries=s.entries.filter(e=>!e.cancelled&&e.work===w.id);return {work:w,entries,byPrep:s.preps.map(p=>({prep:p,kg:entries.reduce((a,e)=>a+prepWeight(e,p.id),0)})),kg:entries.reduce((a,e)=>a+net(e),0),transport:[...new Set(entries.map(e=>[e.route||"Rota não informada",e.vehicle,e.driver].join(" · ")))]}})}

export const isLunchbox=(type:string)=>/marmita/i.test(type);
export const utensilTypes=(s:Production)=>[...new Set([...types,...Object.keys(s.taras),...s.entries.map(e=>e.type)])].filter(type=>!isLunchbox(type));
export const dietLabel=(e:Entry)=>!isLunchbox(e.type)?'':e.diet==='normal'?'Alimentação habitual':e.diet==='especial'?'Alimentação especial/específica':e.diet==='restritiva'?'Alimentação restritiva':'Tipo de alimentação não informado';
export function entryTime(e:Entry){if(e.deviceOffset===undefined)return time(e.at);return new Date(new Date(e.at).getTime()-e.deviceOffset*60000).toLocaleString('pt-BR',{timeZone:'UTC',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'})}
export const LUNCHBOX_WEIGHING_KEY='__marmitas__';
const validDate=(value:string|undefined)=>value&&!Number.isNaN(new Date(value).getTime())?value:null;
const localToday=()=>new Date().toLocaleDateString('en-CA',{timeZone:'America/Bahia'});
export function weighingEntries(s:Production,key:string){return s.entries.filter(e=>!e.cancelled&&(key===LUNCHBOX_WEIGHING_KEY?!!e.lunchboxes:e.prep===key||!!e.lunchboxes?.some(b=>b.components.some(c=>c.prep===key))))}
export function weighingFinishedAt(s:Production,key:string){const saved=validDate(s.weighingFinalizedAt?.[key]);if(saved)return saved;const legacyFinished=s.date<localToday();if(!legacyFinished&&(key===LUNCHBOX_WEIGHING_KEY||!s.preps.find(p=>p.id===key)?.closed))return null;const own=weighingEntries(s,key).map(e=>validDate(e.created)||validDate(e.at)).filter((v):v is string=>!!v).sort().at(-1);if(own)return own;if(!legacyFinished)return null;return s.entries.map(e=>validDate(e.created)||validDate(e.at)).filter((v):v is string=>!!v).sort().at(-1)??s.audit.map(a=>validDate(a.at)).filter((v):v is string=>!!v).sort().at(-1)??null}
export function weighingWindow(s:Production){const entries=s.entries.filter(e=>!e.cancelled),starts=entries.map(e=>validDate(e.at)||validDate(e.created)).filter((v):v is string=>!!v);const start=starts.sort()[0]??s.audit.map(a=>validDate(a.at)).filter((v):v is string=>!!v).sort()[0]??null;const keys=[...s.preps.map(p=>p.id),...(entries.some(e=>e.lunchboxes)?[LUNCHBOX_WEIGHING_KEY]:[])];const finished=keys.map(key=>weighingFinishedAt(s,key));return{start,end:keys.length>0&&finished.every(Boolean)?finished.filter((v):v is string=>!!v).sort().at(-1)??null:null,complete:keys.length>0&&finished.every(Boolean)}}
const normalized=(v:string)=>v.trim().replace(/\s+/g,' ').toLocaleLowerCase('pt-BR');
export const normalizeWorkName=(v:string)=>normalized(v.normalize('NFD').replace(/[\u0300-\u036f]/g,''));
export function consolidateDuplicateWorks(s:Production){const byName=new Map<string,Work>(),ids=new Map<string,string>(),works:Work[]=[];for(const work of s.works){const key=normalizeWorkName(work.name),canonical=byName.get(key);if(!canonical){const clean={...work,name:work.name.trim().replace(/\s+/g,' ')};byName.set(key,clean);works.push(clean);continue}ids.set(work.id,canonical.id);for(const field of ['vehicle','route','driver'] as const)if(!canonical[field]&&work[field])canonical[field]=work[field];for(const field of ['worker','admin','servedWorker','servedAdmin'] as const)if(canonical[field]===null&&work[field]!==null)canonical[field]=work[field];}if(!ids.size)return{production:s,changed:false,merged:0};const entries=s.entries.map(e=>ids.has(e.work)?{...e,work:ids.get(e.work)!}:e);return{production:{...s,works,entries},changed:true,merged:ids.size};}
export function routeDispatch(s:Production){const groups=new Map<string,{key:string;route:string;work:Work;entries:Entry[]}>();for(const e of s.entries.filter(e=>!e.cancelled)){const work=s.works.find(w=>w.id===e.work)??{id:'',name:'Destino a informar',worker:null,admin:null,servedWorker:null,servedAdmin:null,vehicle:'',driver:''};const route=e.route?.trim().replace(/\s+/g,' ')||'Rota não informada';const key=JSON.stringify([normalized(route),normalizeWorkName(work.name)]);if(!groups.has(key))groups.set(key,{key,route,work,entries:[]});groups.get(key)!.entries.push(e)}return [...groups.values()].sort((a,b)=>a.route.localeCompare(b.route,'pt-BR')||a.work.name.localeCompare(b.work.name,'pt-BR')).map(g=>{const lines=new Map<string,{name:string;kg:number;entries:Entry[]}>();for(const e of g.entries){const name=isLunchbox(e.type)?'Marmitas completas':s.preps.find(p=>p.id===e.prep)?.name??'Preparo não identificado';const key=normalized(name);if(!lines.has(key))lines.set(key,{name,kg:0,entries:[]});const row=lines.get(key)!;row.kg+=net(e);row.entries.push(e)}return {...g,kg:g.entries.reduce((a,e)=>a+net(e),0),lines:[...lines.values()],transport:[...new Set(g.entries.map(e=>(e.vehicle||'Veículo a informar')+' / '+(e.driver||'Motorista a informar')))]}})}
export function containerBreakdown(entries:Entry[]){const groups=new Map<string,{label:string;quantity:number;kg:number}>();for(const e of entries){const label=isLunchbox(e.type)?'Marmitas':[e.type,dietLabel(e),e.dietNote?.trim()].filter(Boolean).join(' • ');if(!groups.has(label))groups.set(label,{label,quantity:0,kg:0});const group=groups.get(label)!;group.quantity+=e.quantity;group.kg+=net(e)}return [...groups.values()]}

export function destinationItems(s:Production,g:ReturnType<typeof routeDispatch>[number]){const order=(name:string)=>{const i=names.findIndex(n=>normalized(n)===normalized(name));return i<0?names.length:i};return [...g.lines].sort((a,b)=>order(a.name)-order(b.name)||a.name.localeCompare(b.name,'pt-BR')).flatMap(line=>containerBreakdown(line.entries).map(c=>{const type=c.label.split(' • ')[0];const qualifier=c.label.slice(type.length).replace(/^ • /,'');const plural=c.quantity===1?type:type.startsWith('GN ')?type.replace(/^GN /,'GNs '):type==='Marmita'?'Marmitas':type==='Cuba'?'Cubas':type==='Cooler'?'Coolers':type;if(line.name==='Marmitas completas'){const summary=lunchboxCategorySummary(line.entries);return {...c,food:line.name,text:c.quantity+' Marmitas'+(summary?' ('+summary.replaceAll(' · ','; ')+')':'')}}return {...c,food:line.name,text:c.quantity+' '+plural+' de '+line.name+(qualifier?' ('+qualifier+')':'')}}))}

export function mealDietSummary(e:Entry){const counts=new Map<string,number>();for(const b of e.lunchboxes??[]){const label=(b.diet==='normal'?'habitual':b.diet==='especial'?'especial':b.diet==='restritiva'?'restritiva':'dieta a informar')+(b.dietNote?' — '+b.dietNote:'');counts.set(label,(counts.get(label)??0)+1)}return [...counts].map(([k,v])=>v+' '+k).join('; ')}
export function lunchboxCategoryCounts(entries:Entry[]){let normal=0,special=0,unknown=0;for(const e of entries.filter(e=>isLunchbox(e.type))){if(e.lunchboxes?.length){for(const box of e.lunchboxes){if(box.diet==='normal')normal++;else if(box.diet==='especial'||box.diet==='restritiva')special++;else unknown++;}}else if(e.diet==='normal')normal+=e.quantity;else if(e.diet==='especial'||e.diet==='restritiva')special+=e.quantity;else unknown+=e.quantity;}return{normal,special,unknown,total:normal+special+unknown}}
export function lunchboxCategorySummary(entries:Entry[]){const c=lunchboxCategoryCounts(entries);return [c.normal?c.normal+' '+(c.normal===1?'normal':'normais'):'',c.special?c.special+' '+(c.special===1?'especial':'especiais'):'',c.unknown?c.unknown+' a classificar':''].filter(Boolean).join(' · ')}
export const specialDietNetWeight=(e:Entry)=>{const boxes=e.lunchboxes??[];if(!boxes.length)return isLunchbox(e.type)&&isKnownSpecial(e.diet)?net(e):0;return net(e)*boxes.filter(isSpecialLunchbox).length/boxes.length};
export function specialDietItems(s:Production){const groups=new Map<string,{destination:string;diet:string;item:string;quantity:number;grams:number;units:number;measures:Set<string>}>();for(const e of s.entries.filter(e=>!e.cancelled&&e.lunchboxes)){const destination=s.works.find(w=>w.id===e.work)?.name||'Destino a informar';for(const box of e.lunchboxes!.filter(isSpecialLunchbox)){const diet=(box.diet==='restritiva'?'Restritiva':'Especial')+(box.dietNote?' - '+box.dietNote:'');for(const c of box.components){const item=[c.name,c.item,s.preps.find(p=>p.id===c.prep)?.name].filter(Boolean).join(' - ')||'Item a informar';const key=JSON.stringify([normalizeWorkName(destination),diet,item]);if(!groups.has(key))groups.set(key,{destination,diet,item,quantity:0,grams:0,units:0,measures:new Set()});const row=groups.get(key)!;row.quantity++;row.grams+=c.grams??0;row.units+=c.units??0;if(c.utensil.trim())row.measures.add(c.utensil.trim());}}}return [...groups.values()].map(row=>({...row,measures:[...row.measures]})).sort((a,b)=>a.destination.localeCompare(b.destination,'pt-BR')||a.diet.localeCompare(b.diet,'pt-BR')||a.item.localeCompare(b.item,'pt-BR'));}
export function mealComposition(s:Production,e:Entry){const groups=new Map<string,{count:number;text:string}>();for(const b of e.lunchboxes??[]){const parts=b.components.filter(c=>c.prep||c.item||c.grams!==null||c.units!==null||c.utensil).map(c=>c.name+(c.item?' — '+c.item:'')+(c.prep?' ('+(s.preps.find(p=>p.id===c.prep)?.name??'Preparo a informar')+')':'')+': '+[c.grams===null?'peso a informar':fmt(c.grams,0)+' g',c.units===null?'':c.units+' '+(c.name==='Proteína de caldo'?'conchas':'un.'),c.utensil].filter(Boolean).join(' / '));const text=(parts.join('; ')||'Composição a informar')+' · '+(b.diet||'dieta a informar')+(b.dietNote?' — '+b.dietNote:'');const key=JSON.stringify(b);if(!groups.has(key))groups.set(key,{count:0,text});groups.get(key)!.count++}return [...groups.values()];}
