import {sqliteTable,text,integer,index,uniqueIndex,primaryKey} from 'drizzle-orm/sqlite-core';
export const productions=sqliteTable('productions',{id:text('id').primaryKey(),owner:text('owner').notNull(),date:text('date').notNull(),data:text('data').notNull(),version:integer('version').notNull().default(1),updated:text('updated').notNull(),operator:text('operator'),startedAt:text('started_at'),finishedAt:text('finished_at'),complete:integer('complete'),itemCount:integer('item_count'),summaryVersion:integer('summary_version').notNull().default(0),storage:integer('storage').notNull().default(1)},t=>[index('owner_date').on(t.owner,t.date)]);
export const accounts=sqliteTable('accounts',{id:text('id').primaryKey(),created:text('created').notNull()});
export const accountIdentities=sqliteTable('account_identities',{kind:text('kind').notNull(),value:text('value').notNull(),accountId:text('account_id').notNull().references(()=>accounts.id)},t=>[primaryKey({columns:[t.kind,t.value]}),index('account_identities_account').on(t.accountId)]);
export const requestLimits=sqliteTable('request_limits',{owner:text('owner').notNull(),bucket:integer('bucket').notNull(),hits:integer('hits').notNull()},t=>[uniqueIndex('request_limits_owner_bucket').on(t.owner,t.bucket)]);
export const systemEvents=sqliteTable('system_events',{id:text('id').primaryKey(),event:text('event').notNull(),affected:integer('affected').notNull(),at:text('at').notNull()});
export const dataFixLog=sqliteTable('data_fix_log',{id:text('id').primaryKey(),fix:text('fix').notNull(),tableName:text('table_name').notNull(),rowId:text('row_id').notNull(),field:text('field').notNull(),before:text('before'),after:text('after'),at:text('at').notNull()},t=>[index('data_fix_log_fix').on(t.fix,t.rowId)]);
export const menuCatalogs=sqliteTable('menu_catalogs',{owner:text('owner').primaryKey(),data:text('data').notNull(),version:integer('version').notNull().default(1),updated:text('updated').notNull()});
export const hourSettings=sqliteTable('hour_settings',{owner:text('owner').primaryKey(),data:text('data').notNull()});
export const hourPeriods=sqliteTable('hour_periods',{id:text('id').primaryKey(),owner:text('owner').notNull(),activity:text('activity').notNull(),production:text('production').notNull(),start:integer('start').notNull(),end:integer('end'),rate:integer('rate').notNull(),reviewed:integer('reviewed').notNull().default(0)},t=>[index('hour_periods_owner_start').on(t.owner,t.start)]);
// Active periods use a separate unique owner slot. Inserts and stops update it
// in a D1 batch transaction; a duplicate slot rolls back the entire start.
export const hourActive=sqliteTable('hour_active',{owner:text('owner').primaryKey(),period:text('period').notNull().references(()=>hourPeriods.id),pause:integer('pause'),resume:integer('resume')});
export const hourEvidence=sqliteTable('hour_evidence',{id:text('id').primaryKey(),owner:text('owner').notNull(),period:text('period').notNull().references(()=>hourPeriods.id),key:text('key').notNull(),name:text('name').notNull(),size:integer('size').notNull(),hash:text('hash').notNull(),at:text('at').notNull()},t=>[index('hour_evidence_owner_period').on(t.owner,t.period)]);
export const hourArchives=sqliteTable('hour_archives',{id:text('id').primaryKey(),owner:text('owner').notNull(),month:text('month').notNull(),start:integer('start').notNull(),end:integer('end').notNull(),at:text('at').notNull(),data:text('data').notNull()},t=>[uniqueIndex('hour_archives_owner_month').on(t.owner,t.month)]);
export const hourRevisions=sqliteTable('hour_revisions',{id:text('id').primaryKey(),owner:text('owner').notNull(),period:text('period').notNull().references(()=>hourPeriods.id),oldEnd:integer('old_end').notNull(),newEnd:integer('new_end').notNull(),reason:text('reason').notNull(),at:integer('at').notNull()},t=>[index('hour_revisions_owner_period').on(t.owner,t.period)]);
export const hourManual=sqliteTable('hour_manual',{period:text('period').primaryKey().references(()=>hourPeriods.id),owner:text('owner').notNull(),at:integer('at').notNull(),pause:integer('pause'),resume:integer('resume'),result:text('result').notNull().default('')});
export const hourGoals=sqliteTable('hour_goals',{owner:text('owner').notNull(),month:text('month').notNull(),cents:integer('cents').notNull()},t=>[uniqueIndex('hour_goals_owner_month').on(t.owner,t.month)]);
export const productionAudit=sqliteTable('production_audit',{id:text('id').primaryKey(),productionId:text('production_id').notNull(),owner:text('owner').notNull(),at:text('at').notNull(),account:text('account').notNull(),operator:text('operator').notNull(),action:text('action').notNull(),reason:text('reason'),changes:text('changes').notNull()},t=>[index('production_audit_prod').on(t.productionId,t.at)]);
export const productionEntries=sqliteTable('production_entries',{id:text('id').notNull(),productionId:text('production_id').notNull(),owner:text('owner').notNull(),prepId:text('prep_id'),workId:text('work_id'),kind:text('kind').notNull(),data:text('data').notNull(),created:text('created').notNull(),updated:text('updated').notNull(),cancelled:integer('cancelled').notNull().default(0)},t=>[primaryKey({columns:[t.productionId,t.id]}),index('production_entries_prod').on(t.productionId,t.id)]);
export const technicalSheets=sqliteTable('technical_sheets',{id:text('id').primaryKey(),owner:text('owner').notNull(),name:text('name').notNull(),category:text('category').notNull().default('Preparo'),data:text('data').notNull(),version:integer('version').notNull().default(1),archived:integer('archived').notNull().default(0),updated:text('updated').notNull(),updatedBy:text('updated_by').notNull().default('')},t=>[index('technical_sheets_owner').on(t.owner,t.archived,t.updated)]);
export const technicalSheetRevisions=sqliteTable('technical_sheet_revisions',{id:text('id').primaryKey(),sheetId:text('sheet_id').notNull(),owner:text('owner').notNull(),revision:integer('revision').notNull(),data:text('data').notNull(),at:text('at').notNull(),account:text('account').notNull()},t=>[uniqueIndex('technical_sheet_revisions_sheet_revision').on(t.sheetId,t.revision),index('technical_sheet_revisions_owner').on(t.owner,t.sheetId,t.revision)]);
export const equipment=sqliteTable('equipment',{id:text('id').primaryKey(),owner:text('owner').notNull(),name:text('name').notNull(),category:text('category').notNull(),data:text('data').notNull(),version:integer('version').notNull().default(1),archived:integer('archived').notNull().default(0),updated:text('updated').notNull()},t=>[index('equipment_owner').on(t.owner,t.archived,t.updated)]);
