import {sqliteTable,text,integer,index,uniqueIndex} from 'drizzle-orm/sqlite-core';
export const productions=sqliteTable('productions',{id:text('id').primaryKey(),owner:text('owner').notNull(),date:text('date').notNull(),data:text('data').notNull(),version:integer('version').notNull().default(1),updated:text('updated').notNull()},t=>[index('owner_date').on(t.owner,t.date)]);
export const requestLimits=sqliteTable('request_limits',{owner:text('owner').notNull(),bucket:integer('bucket').notNull(),hits:integer('hits').notNull()},t=>[uniqueIndex('request_limits_owner_bucket').on(t.owner,t.bucket)]);
export const systemEvents=sqliteTable('system_events',{id:text('id').primaryKey(),event:text('event').notNull(),affected:integer('affected').notNull(),at:text('at').notNull()});
export const dataFixLog=sqliteTable('data_fix_log',{id:text('id').primaryKey(),fix:text('fix').notNull(),tableName:text('table_name').notNull(),rowId:text('row_id').notNull(),field:text('field').notNull(),before:text('before'),after:text('after'),at:text('at').notNull()},t=>[index('data_fix_log_fix').on(t.fix,t.rowId)]);
export const menuCatalogs=sqliteTable('menu_catalogs',{owner:text('owner').primaryKey(),data:text('data').notNull(),version:integer('version').notNull().default(1),updated:text('updated').notNull()});
export const hourSettings=sqliteTable('hour_settings',{owner:text('owner').primaryKey(),data:text('data').notNull()});
export const hourPeriods=sqliteTable('hour_periods',{id:text('id').primaryKey(),owner:text('owner').notNull(),activity:text('activity').notNull(),production:text('production').notNull(),start:integer('start').notNull(),end:integer('end'),rate:integer('rate').notNull(),reviewed:integer('reviewed').notNull().default(0)},t=>[index('hour_periods_owner_start').on(t.owner,t.start)]);
// Active periods use a separate unique owner slot. Inserts and stops update it
// in a D1 batch transaction; a duplicate slot rolls back the entire start.
export const hourActive=sqliteTable('hour_active',{owner:text('owner').primaryKey(),period:text('period').notNull().references(()=>hourPeriods.id),pause:integer('pause'),resume:integer('resume')});
export const hourEvidence=sqliteTable('hour_evidence',{id:text('id').primaryKey(),owner:text('owner').notNull(),period:text('period').notNull().references(()=>hourPeriods.id),key:text('key').notNull(),name:text('name').notNull(),size:integer('size').notNull(),hash:text('hash').notNull(),at:text('at').notNull()},t=>[index('hour_evidence_owner_period').on(t.owner,t.period)]);
export const hourArchives=sqliteTable('hour_archives',{id:text('id').primaryKey(),owner:text('owner').notNull(),month:text('month').notNull(),start:integer('start').notNull(),end:integer('end').notNull(),at:text('at').notNull(),data:text('data').notNull()},t=>[uniqueIndex('hour_archives_owner_month').on(t.owner,t.month)]);
export const hourRevisions=sqliteTable('hour_revisions',{id:text('id').primaryKey(),owner:text('owner').notNull(),period:text('period').notNull().references(()=>hourPeriods.id),oldEnd:integer('old_end').notNull(),newEnd:integer('new_end').notNull(),reason:text('reason').notNull(),at:integer('at').notNull()},t=>[index('hour_revisions_owner_period').on(t.owner,t.period)]);
export const hourManual=sqliteTable('hour_manual',{period:text('period').primaryKey().references(()=>hourPeriods.id),owner:text('owner').notNull(),at:integer('at').notNull(),pause:integer('pause'),resume:integer('resume'),result:text('result').notNull().default('')});
export const hourGoals=sqliteTable('hour_goals',{owner:text('owner').notNull(),month:text('month').notNull(),cents:integer('cents').notNull()},t=>[uniqueIndex('hour_goals_owner_month').on(t.owner,t.month)]);
