'use client';
import {useState,useRef,useEffect} from 'react';
import {Button} from '@/components/ui/button';
import {Entry,Production,Lunchbox,MealComponent,utensilTypes,isLunchbox,num,fmt} from '@/lib/uan';
import {toast} from 'sonner';
import {preparationMatches} from '@/lib/menu-catalog';
import {useConfirmAction} from '@/components/ui/confirm-action';

const componentNames=['Arroz','Feijão','Macarrão','Proteína 1','Proteína 2'];
const MAX_LUNCHBOXES=5000;
const LUNCHBOX_PAGE_SIZE=50;
function Input({label,value,onChange,numeric=false}:{label:string;value:string;onChange:(v:string)=>void;numeric?:boolean}){return <label className="field"><span>{label}</span><input value={value} inputMode={numeric?'decimal':undefined} onChange={e=>onChange(e.target.value)}/></label>}
export default function EntryForm({production:s,prep,initial,busy,onSave,onDone,lunchboxesMode=false}:{production:Production;prep:string;initial?:Entry;busy:boolean;preparationOptions?:string[];lunchboxesMode?:boolean;onSave:(entry:Entry)=>Promise<boolean>;onDone?:()=>void}){
 const confirmation=useConfirmAction();
 const [draftId,setDraftId]=useState(initial?.id??crypto.randomUUID());const attemptTime=useRef<string|null>(null);
 const lunchboxEntry=lunchboxesMode||!!initial?.lunchboxes;
 const initialMealCategory=()=>{const diets=initial?.lunchboxes?.map(b=>b.diet).filter(Boolean)??[];if(!diets.length)return initial?.diet==='normal'?'normal':initial?.diet==='especial'||initial?.diet==='restritiva'?'especial':'';if(diets.every(d=>d==='normal'))return'normal';if(diets.every(d=>d==='especial'||d==='restritiva'))return'especial';return'mista'};
 const [mealCategory,setMealCategory]=useState(initialMealCategory());
 const [rec,setRec]=useState({...initial,prep:initial?.prep??prep,type:lunchboxEntry?'Marmita':initial?.type??'GN M',work:initial?.work??'',vehicle:initial?.vehicle??'',driver:initial?.driver??'',route:initial?.route??'',note:initial?.note??'',diet:initial?.diet??'',dietNote:initial?.dietNote??''});
 const [countDraft,setCountDraft]=useState(String(initial?.quantity??1));
 const [quantity,setQuantity]=useState(String(initial?.quantity??1)),[gross,setGross]=useState(initial?String(initial.gross):''),[tare,setTare]=useState(initial?String(initial.tare):String(s.taras[lunchboxEntry?'Marmita':'GN M']??'')),[temperature,setTemperature]=useState(initial?.temperature==null?'':String(initial.temperature));
 const blank=():Lunchbox=>({diet:mealCategory==='normal'?'normal':mealCategory==='especial'?'especial':'',dietNote:'',components:componentNames.map(name=>({name,prep:s.preps.find(p=>p.name.toLocaleLowerCase('pt-BR')===name.toLocaleLowerCase('pt-BR'))?.id??'',grams:null,units:null,utensil:''}))});
 const [expanded,setExpanded]=useState(new Set([0]));
 const [mealPage,setMealPage]=useState(0);
 const [boxes,setBoxes]=useState<Lunchbox[]>(initial?.lunchboxes??(lunchboxEntry?[blank()]:[]));
 const meal=lunchboxEntry||isLunchbox(rec.type),composed=meal&&boxes.length>0;
 const edit=(key:string,value:string)=>setRec(r=>({...r,[key]:value}));
 function count(v:string){setCountDraft(v);setQuantity(v);const n=num(v);if(meal&&n!==null&&Number.isInteger(n)&&n>=1&&n<=MAX_LUNCHBOXES){setBoxes(old=>Array.from({length:n},(_,i)=>old[i]??blank()));setMealPage(p=>Math.min(p,Math.ceil(n/LUNCHBOX_PAGE_SIZE)-1));}}
 function component(i:number,j:number,patch:Partial<MealComponent>){setBoxes(old=>{const next=old.slice();next[i]={...old[i],components:old[i].components.map((c,l)=>l===j?{...c,...patch}:c)};return next;});}
 function diet(i:number,key:string,value:string){setBoxes(old=>{const next=old.slice();next[i]={...old[i],[key]:value};return next;});}
 function classifyMeals(value:string){setMealCategory(value);if(value==='normal'||value==='especial')setBoxes(old=>old.map(box=>({...box,diet:value,dietNote:value==='normal'?'':box.dietNote})));}
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(gross&&!initial){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[gross,initial]);
 const componentKg=boxes.reduce((sum,b)=>sum+b.components.reduce((a,c)=>a+(c.grams??0),0),0)/1000;
 async function submit(e:React.FormEvent){e.preventDefault();const q=num(countDraft),g=num(gross),ta=num(tare),temp=num(temperature);if(meal&&!mealCategory)return toast.error('Selecione se as marmitas são normais ou especiais.');if(q===null||q<1||!Number.isInteger(q)||meal&&q>MAX_LUNCHBOXES||g===null||ta===null||ta<0||g<=q*ta)return toast.error('Confira quantidade, tara e peso na balança. O peso deve superar a tara total.');if(temperature.trim()&&temp===null||temp!==null&&(temp< -50||temp>150))return toast.error('Confira a temperatura.');if(composed&&boxes.length!==q)return toast.error('Confira a quantidade de marmitas.');const now=new Date();attemptTime.current??=now.toISOString();const entry:Entry={...rec,id:draftId,prep:composed?'':rec.prep,quantity:q,gross:g,tare:ta,temperature:temp,operator:s.operator,at:initial?.at??attemptTime.current,created:initial?.created??attemptTime.current,deviceOffset:initial?.deviceOffset??now.getTimezoneOffset(),cancelled:initial?.cancelled??false,lunchboxes:composed?boxes.map(b=>({...b,diet:b.diet||undefined})):undefined,diet:mealCategory==='normal'||mealCategory==='especial'?mealCategory:rec.diet||undefined};if(await onSave(entry)){if(initial)onDone?.();else {setDraftId(crypto.randomUUID());attemptTime.current=null;setGross('');setTemperature('');toast.success('Pronto para a próxima pesagem.');}}}
 return <form onSubmit={submit} className="collection-form">
 <p className="notice">{meal?'Salve o grupo de marmitas, a quantidade, a tara e o peso agora.':'Salve recipiente, quantidade, tara e peso agora.'} Obra, transporte e temperatura podem ser preenchidos depois em “Editar”. O horário original será preservado.</p>
 <div className="grid2">{meal?<label className="field"><span>Preparo</span><input value="Marmitas" readOnly aria-readonly="true"/></label>:<label className="field"><span>Recipiente</span><select value={rec.type} onChange={e=>{const type=e.target.value;edit('type',type);setTare(String(s.taras[type]??''));setBoxes([]);}}>{utensilTypes(s).map(t=><option key={t}>{t}</option>)}</select></label>}
 {meal&&<label className="field"><span>Tipo das marmitas</span><select required value={mealCategory} onChange={e=>classifyMeals(e.target.value)}><option value="">Selecione</option><option value="normal">Normais</option><option value="especial">Especiais</option>{mealCategory==='mista'&&<option value="mista">Registro antigo misto</option>}</select></label>}
 <label className="field"><span>{meal?'Quantas marmitas serão enviadas? (1 a 5.000)':'Quantidade de recipientes'}</span><input type="number" min={1} max={meal?MAX_LUNCHBOXES:undefined} step={1} required value={countDraft} onChange={e=>setCountDraft(e.target.value)} onBlur={async e=>{const n=num(e.target.value);if(n===null||!Number.isInteger(n)||n<1||meal&&n>MAX_LUNCHBOXES){toast.error('Informe uma quantidade inteira'+(meal?' de 1 a 5.000.':'.'));return}if(boxes.length>n&&!await confirmation.confirm('A composição das últimas marmitas será removida.','Reduzir quantidade','Reduzir')){setCountDraft(quantity);return}count(e.target.value);}}/></label>
 <Input label={meal?'Tara de cada marmita vazia (kg)':'Tara de cada recipiente vazio (kg)'} numeric value={tare} onChange={setTare}/><Input label={meal?'Peso total na balança, com todas as marmitas (kg)':'Peso total na balança, com todos os recipientes (kg)'} numeric value={gross} onChange={setGross}/></div>
 <p className="weight-result">Alimento sem recipientes: <strong>{num(gross)!==null&&num(tare)!==null&&num(quantity)!==null?fmt(num(gross)!-num(tare)!*(num(countDraft)??1),3):'—'} kg</strong></p>
 {meal&&!composed&&<Button type="button" variant="outline" onClick={()=>{setQuantity('1');setBoxes([blank()]);}}>Detalhar composição da marmita</Button>}
 {composed&&<section className="meal-composition"><h3>Composição de cada marmita</h3><p className="footnote">Preencha o que conseguir e complete depois. Gramas são por marmita, nunca o total do lote. Para proteínas, informe unidades e, se pesar, também gramas. Digite o nome usado no lote em “Preparo utilizado”; quando ele coincidir com um preparo aberto, as gramas serão alocadas ao rendimento.</p>
 {boxes.length>1&&<Button type="button" variant="outline" onClick={async()=>{if(await confirmation.confirm('A composição e a dieta da marmita 1 substituirão os campos das demais.','Repetir composição','Substituir'))setBoxes(boxes.map(()=>structuredClone(boxes[0])));}}>Repetir marmita 1 nas demais</Button>}
{boxes.length>LUNCHBOX_PAGE_SIZE&&<div className="meal-pages"><Button type="button" variant="outline" disabled={mealPage===0} onClick={()=>setMealPage(p=>Math.max(0,p-1))}>Marmitas anteriores</Button><span>{mealPage*LUNCHBOX_PAGE_SIZE+1}–{Math.min((mealPage+1)*LUNCHBOX_PAGE_SIZE,boxes.length)} de {boxes.length}</span><Button type="button" variant="outline" disabled={(mealPage+1)*LUNCHBOX_PAGE_SIZE>=boxes.length} onClick={()=>setMealPage(p=>p+1)}>Próximas marmitas</Button></div>}
 {boxes.slice(mealPage*LUNCHBOX_PAGE_SIZE,(mealPage+1)*LUNCHBOX_PAGE_SIZE).map((box,offset)=>{const i=mealPage*LUNCHBOX_PAGE_SIZE+offset;return <details key={i} open={expanded.has(i)} onToggle={e=>{const open=e.currentTarget.open;setExpanded(old=>{if(old.has(i)===open)return old;const next=new Set(old);if(open)next.add(i);else next.delete(i);return next;});}} className="panel"><summary>Marmita {i+1} · {fmt(box.components.reduce((a,c)=>a+(c.grams??0),0),0)} g informados</summary>
 {expanded.has(i)&&<>
 {(mealCategory==='especial'||mealCategory==='mista'&&box.diet!=='normal')&&<Input label="Orientação da dieta especial (sem dados pessoais)" value={box.dietNote??''} onChange={v=>diet(i,'dietNote',v)}/>}
 {box.components.map((c,j)=>c.name==='Proteína de caldo'?null:<div key={j} className="meal-component"><h4>{c.name}</h4><div className="grid2"><label className="field"><span>Preparo utilizado</span><input value={c.item?.trim()?c.item:s.preps.find(p=>p.id===c.prep)?.name??''} placeholder={j>=3?'Digite o nome da proteína':'Digite o nome do preparo'} onChange={e=>{const item=e.target.value;const linked=s.preps.find(p=>preparationMatches(p.name,item));component(i,j,{item,prep:linked?.id??''});}}/></label><label className="field"><span>Peso do alimento (g)</span><input type="number" min={0} step="any" value={c.grams??''} onChange={e=>component(i,j,{grams:num(e.target.value)})}/></label>{j>=3&&<label className="field"><span>Quantidade de unidades</span><input type="number" min={0} step={1} value={c.units??''} onChange={e=>component(i,j,{units:num(e.target.value)})}/></label>}<label className="field"><span>Medida caseira utilizada</span><input value={c.utensil} placeholder="Ex.: concha média, colher de servir ou pegador" onChange={e=>component(i,j,{utensil:e.target.value})}/></label></div></div>)}</>}</details>})}
 <p className="footnote">Componentes informados: {fmt(componentKg,3)} kg. O peso total da balança é contado uma única vez. Pesos ainda sem preparo identificado ficam sem alocação.</p></section>}
 <details open={!!initial}><summary>Obra, rota e transporte — opcionais</summary><label className="field"><span>Obra / canteiro de destino</span><select value={rec.work} onChange={e=>{const w=s.works.find(w=>w.id===e.target.value);setRec(r=>({...r,work:e.target.value,vehicle:w?.vehicle||r.vehicle,driver:w?.driver||r.driver,route:w?.route||r.route}));}}><option value="">Destino a informar</option>{s.works.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><div className="grid2"><Input label="Veículo / placa" value={rec.vehicle} onChange={v=>edit('vehicle',v)}/><Input label="Motorista" value={rec.driver} onChange={v=>edit('driver',v)}/><Input label="Rota / viagem" value={rec.route} onChange={v=>edit('route',v)}/></div></details>
 <Input label="Temperatura (°C) — opcional" numeric value={temperature} onChange={setTemperature}/><Input label="Observação / ação tomada" value={rec.note} onChange={v=>edit('note',v)}/>
 {num(temperature)!==null&&num(temperature)!<=60&&<p className="alert danger">Temperatura em alerta. Registre a avaliação e a ação tomada pelo RT; salvar não libera o alimento para consumo.</p>}
 <Button type="submit" disabled={busy}>{busy?'Salvando…':initial?'Salvar alterações':meal?'Salvar grupo de marmitas':'Salvar recipiente e peso'}</Button><p className="footnote">Aguarde “Registro salvo”. Registros sem obra ficam em “Destino a informar” no painel e PDF.</p>{confirmation.dialog}
 </form>;
}
