'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {num} from '@/lib/uan';
import type {Equipment,MenuCatalog} from '@/lib/menu-catalog';
import {toast} from 'sonner';

const categories=['Panela','Faca','Tábua de corte','Escumadeira','Garfo','Caldeira','Forno combinado','Balde medidor','Remo','GN','Outro'];
const blank=():Equipment=>({id:crypto.randomUUID(),name:'',category:'Panela',number:'',size:'',weightKg:null,capacity:'',notes:''});
export default function EquipmentPanel({catalog,busy,onSave}:{catalog:MenuCatalog;busy:boolean;onSave:(next:MenuCatalog)=>Promise<boolean>}){
 const [draft,setDraft]=useState<Equipment>(blank()),[editing,setEditing]=useState('');const equipment=catalog.equipment??[];
 async function submit(e:React.FormEvent){e.preventDefault();const item={...draft,name:draft.name.trim().replace(/\s+/g,' '),category:draft.category.trim(),number:draft.number.trim(),size:draft.size.trim(),capacity:draft.capacity.trim(),notes:draft.notes.trim()};if(!item.name||!item.category)return toast.error('Informe o nome e a categoria.');if(equipment.some(x=>x.id!==editing&&[x.name,x.number].join('|').toLocaleLowerCase('pt-BR')===[item.name,item.number].join('|').toLocaleLowerCase('pt-BR')))return toast.error('Esse utensílio ou equipamento já está cadastrado.');const next=editing?equipment.map(x=>x.id===editing?item:x):[...equipment,item];if(await onSave({...catalog,equipment:next})){setEditing('');setDraft(blank());toast.success('Utensílio/equipamento salvo.')}}
 return <section className="panel equipment-manager"><div className="panel-title"><div><h3>Utensílios e equipamentos da cozinha</h3><p className="muted">Cadastro central para fichas técnicas e demais áreas do sistema.</p></div></div><form onSubmit={submit}><div className="grid2"><label className="field"><span>Categoria</span><select value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label className="field"><span>Nome</span><input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="Ex.: Caldeira a gás" required/></label><label className="field"><span>Numeração/identificação</span><input value={draft.number} onChange={e=>setDraft({...draft,number:e.target.value})} placeholder="Ex.: 03"/></label><label className="field"><span>Tamanho/modelo</span><input value={draft.size} onChange={e=>setDraft({...draft,size:e.target.value})} placeholder="Ex.: GN 1/1 ou panela 80 cm"/></label><label className="field"><span>Peso vazio (kg)</span><input value={draft.weightKg??''} onChange={e=>setDraft({...draft,weightKg:num(e.target.value)})} inputMode="decimal"/></label><label className="field"><span>Capacidade/volume</span><input value={draft.capacity} onChange={e=>setDraft({...draft,capacity:e.target.value})} placeholder="Ex.: 200 L ou 20 GNs"/></label></div><label className="field"><span>Observações</span><textarea value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})} maxLength={300}/></label><div className="panel-actions"><Button type="submit" disabled={busy}>{editing?'Atualizar cadastro':'Adicionar ao cadastro'}</Button>{editing&&<Button type="button" variant="outline" onClick={()=>{setEditing('');setDraft(blank())}}>Cancelar</Button>}</div></form><div className="equipment-list">{equipment.map(item=><article key={item.id}><div><strong>{item.name}{item.number?' · Nº '+item.number:''}</strong><small>{[item.category,item.size,item.capacity,item.weightKg!==null?item.weightKg.toLocaleString('pt-BR')+' kg':''].filter(Boolean).join(' · ')}</small></div><div className="panel-actions"><Button type="button" variant="outline" onClick={()=>{setEditing(item.id);setDraft({...item})}}>Editar</Button><Button type="button" variant="ghost" disabled={busy} onClick={async()=>{if(window.confirm('Remover este cadastro? Fichas antigas manterão a referência, mas o item deixará de aparecer para novas seleções.'))await onSave({...catalog,equipment:equipment.filter(x=>x.id!==item.id)})}}>Remover</Button></div></article>)}{equipment.length===0&&<p className="muted">Nenhum utensílio ou equipamento cadastrado.</p>}</div></section>;
}
