'use client';
import {useEffect,useMemo,useState} from 'react';
import {Button} from '@/components/ui/button';
import {money,num} from '@/lib/uan';
import {technicalSheetCost,type MenuCatalog,type TechnicalCost,type TechnicalIngredient,type TechnicalSheet} from '@/lib/menu-catalog';
import {toast} from 'sonner';

const emptyIngredient=():TechnicalIngredient=>({name:'',qty:0,unit:'kg',unitPrice:0});
const emptyCost=():TechnicalCost=>({name:'',value:0});
const blank=(preparation=''):TechnicalSheet=>({id:crypto.randomUUID(),preparation,yieldKg:null,portions:null,portionGrams:null,ingredients:[emptyIngredient()],additionalCosts:[],instructions:''});

export default function TechnicalSheetsPanel({catalog,busy,onSave}:{catalog:MenuCatalog;busy:boolean;onSave:(next:MenuCatalog)=>Promise<boolean>}){
 const [selected,setSelected]=useState(''),[draft,setDraft]=useState<TechnicalSheet>(()=>blank());
 const sheets=catalog.technicalSheets??[];
 useEffect(()=>{if(selected&&!sheets.some(x=>x.id===selected)){setSelected('');setDraft(blank())}},[selected,sheets]);
 const total=useMemo(()=>technicalSheetCost(draft),[draft]);
 function edit(id:string){const sheet=sheets.find(x=>x.id===id);if(sheet){setSelected(id);setDraft(structuredClone(sheet))}}
 function number(value:string){return num(value)}
 function updateIngredient(index:number,key:keyof TechnicalIngredient,value:string){setDraft(current=>({...current,ingredients:current.ingredients.map((row,i)=>i===index?{...row,[key]:key==='name'||key==='unit'?value:number(value)??0}:row)}))}
 function updateCost(index:number,key:keyof TechnicalCost,value:string){setDraft(current=>({...current,additionalCosts:current.additionalCosts.map((row,i)=>i===index?{...row,[key]:key==='name'?value:number(value)??0}:row)}))}
 async function submit(e:React.FormEvent){e.preventDefault();const preparation=draft.preparation.trim().replace(/\s+/g,' '),ingredients=draft.ingredients.filter(x=>x.name.trim()&&x.qty>0).map(x=>({...x,name:x.name.trim(),unit:x.unit.trim()})),additionalCosts=draft.additionalCosts.filter(x=>x.name.trim()).map(x=>({...x,name:x.name.trim()}));if(!preparation)return toast.error('Informe o nome do preparo.');if(!ingredients.length)return toast.error('Cadastre pelo menos um ingrediente com quantidade.');const sheet={...draft,preparation,ingredients,additionalCosts};const preparations=catalog.preparations.some(x=>x.toLocaleLowerCase('pt-BR')===preparation.toLocaleLowerCase('pt-BR'))?catalog.preparations:[...catalog.preparations,preparation];const technicalSheets=selected?sheets.map(x=>x.id===selected?sheet:x):[...sheets,sheet];if(await onSave({...catalog,preparations,technicalSheets})){setSelected(sheet.id);setDraft(sheet);toast.success('Ficha técnica salva.')}}
 return <section className="panel technical-sheets"><div className="panel-title"><div><h3>Fichas técnicas</h3><p className="muted">Ingredientes, custos e rendimento padrão de cada preparo.</p></div><Button type="button" variant="outline" onClick={()=>{setSelected('');setDraft(blank())}}>+ Nova ficha</Button></div>
 {sheets.length>0&&<label className="field"><span>Ficha cadastrada</span><select value={selected} onChange={e=>e.target.value?edit(e.target.value):(setSelected(''),setDraft(blank()))}><option value="">Nova ficha técnica</option>{sheets.map(sheet=><option key={sheet.id} value={sheet.id}>{sheet.preparation}</option>)}</select></label>}
 <form onSubmit={submit}><label className="field"><span>Nome do preparo</span><input list="technical-preparations" value={draft.preparation} onChange={e=>setDraft({...draft,preparation:e.target.value})} required maxLength={160}/><datalist id="technical-preparations">{catalog.preparations.map(item=><option key={item} value={item}/>)}</datalist></label>
 <div className="grid2"><label className="field"><span>Rendimento pronto (kg)</span><input value={draft.yieldKg??''} onChange={e=>setDraft({...draft,yieldKg:number(e.target.value)})} inputMode="decimal"/></label><label className="field"><span>Número de porções</span><input value={draft.portions??''} onChange={e=>setDraft({...draft,portions:number(e.target.value)})} inputMode="numeric"/></label><label className="field"><span>Porção padrão (g)</span><input value={draft.portionGrams??''} onChange={e=>setDraft({...draft,portionGrams:number(e.target.value)})} inputMode="decimal"/></label></div>
 <h4>Ingredientes</h4>{draft.ingredients.map((row,index)=><div className="technical-row" key={index}><label className="field"><span>Ingrediente</span><input value={row.name} onChange={e=>updateIngredient(index,'name',e.target.value)} maxLength={100}/></label><div className="grid2"><label className="field"><span>Quantidade</span><input value={row.qty||''} onChange={e=>updateIngredient(index,'qty',e.target.value)} inputMode="decimal"/></label><label className="field"><span>Unidade</span><input value={row.unit} onChange={e=>updateIngredient(index,'unit',e.target.value)} maxLength={20}/></label><label className="field"><span>Preço por unidade (R$)</span><input value={row.unitPrice||''} onChange={e=>updateIngredient(index,'unitPrice',e.target.value)} inputMode="decimal"/></label><div className="field"><span>Subtotal</span><strong>{money(row.qty*row.unitPrice)}</strong><Button type="button" variant="ghost" disabled={draft.ingredients.length===1} onClick={()=>setDraft({...draft,ingredients:draft.ingredients.filter((_,i)=>i!==index)})}>Remover</Button></div></div></div>)}
 <Button type="button" variant="outline" onClick={()=>setDraft({...draft,ingredients:[...draft.ingredients,emptyIngredient()]})}>+ Ingrediente</Button>
 <details><summary>Outros custos do preparo</summary>{draft.additionalCosts.map((row,index)=><div className="grid2 technical-row" key={index}><label className="field"><span>Descrição</span><input value={row.name} onChange={e=>updateCost(index,'name',e.target.value)} maxLength={100}/></label><label className="field"><span>Valor (R$)</span><input value={row.value||''} onChange={e=>updateCost(index,'value',e.target.value)} inputMode="decimal"/></label><Button type="button" variant="ghost" onClick={()=>setDraft({...draft,additionalCosts:draft.additionalCosts.filter((_,i)=>i!==index)})}>Remover</Button></div>)}<Button type="button" variant="outline" onClick={()=>setDraft({...draft,additionalCosts:[...draft.additionalCosts,emptyCost()]})}>+ Outro custo</Button></details>
 <label className="field"><span>Modo de preparo e observações técnicas</span><textarea rows={5} maxLength={3000} value={draft.instructions} onChange={e=>setDraft({...draft,instructions:e.target.value})}/></label><div className="weight-result"><span>Custo total da ficha</span><strong>{money(total)}</strong></div><Button className="save-button" type="submit" disabled={busy}>Salvar ficha técnica</Button>
 {selected&&<Button type="button" variant="ghost" disabled={busy} onClick={async()=>{if(window.confirm('Remover esta ficha técnica? As produções já registradas não serão alteradas.')&&await onSave({...catalog,technicalSheets:sheets.filter(x=>x.id!==selected)})){setSelected('');setDraft(blank());toast.success('Ficha técnica removida.')}}}>Remover ficha</Button>}</form></section>;
}
